# Generated by hand to migrate plain steps text to RecipeStep model

from django.db import migrations
import re

def extract_duration(text):
    # Match patterns like: "bake for 45 minutes", "simmer for 1 hour", "15 mins", "1 hour 30 mins", etc.
    # 1. Hour + minute pattern: e.g., "1 hour 30 minutes" or "1 hr 30 mins"
    hr_min_match = re.search(
        r'\b(\d+)\s*(?:hour|hr)s?\s*(?:and\s*)?(\d+)\s*(?:min|minute)s?\b', 
        text, 
        re.IGNORECASE
    )
    if hr_min_match:
        return int(hr_min_match.group(1)) * 60 + int(hr_min_match.group(2))
        
    # 2. Hours only pattern: e.g., "1 hour" or "2 hrs"
    hr_match = re.search(r'\b(\d+)\s*(?:hour|hr)s?\b', text, re.IGNORECASE)
    if hr_match:
        return int(hr_match.group(1)) * 60
        
    # 3. Minutes only pattern: e.g., "15 minutes" or "10 mins"
    min_match = re.search(r'\b(\d+)\s*(?:min|minute)s?\b', text, re.IGNORECASE)
    if min_match:
        return int(min_match.group(1))
        
    return None

def migrate_plain_steps_to_structured(apps, schema_editor):
    Recipe = apps.get_model('recipes', 'Recipe')
    RecipeStep = apps.get_model('recipes', 'RecipeStep')

    for recipe in Recipe.objects.all():
        if not recipe.steps:
            continue
        
        # Split step text by newlines/carriage returns
        lines = [line.strip() for line in re.split(r'\r?\n', recipe.steps)]
        # Filter out empty lines
        lines = [line for line in lines if line]
        
        for index, line in enumerate(lines):
            duration = extract_duration(line)
            # Create the RecipeStep row
            RecipeStep.objects.create(
                recipe=recipe,
                text=line,
                duration_minutes=duration,
                order=index
            )

def rollback_structured_steps_to_plain(apps, schema_editor):
    Recipe = apps.get_model('recipes', 'Recipe')
    
    for recipe in Recipe.objects.all():
        # Get all steps associated with the recipe (using steps_new related_name)
        steps = recipe.steps_new.all().order_by('order')
        if steps.exists():
            recipe.steps = "\n".join([step.text for step in steps])
            recipe.save()

class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipestep'),
    ]

    operations = [
        migrations.RunPython(
            migrate_plain_steps_to_structured,
            reverse_code=rollback_structured_steps_to_plain
        ),
    ]
