# Generated by Django 4.2.30 on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_remove_recipe_steps_alter_recipestep_recipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppinglistitem",
            name="is_custom",
            field=models.BooleanField(default=False),
        ),
    ]
