# Generated by Django 4.2.30 on 2026-06-05 06:19

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_shoppinglistitem_is_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplanentry',
            name='pantry_consumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PantryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit', models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('tsp', 'tsp'), ('tbsp', 'tbsp'), ('item', 'item'), ('pack', 'pack')], max_length=8)),
                ('note', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.ingredient')),
            ],
            options={
                'ordering': ['ingredient__name', 'unit'],
                'unique_together': {('ingredient', 'unit')},
            },
        ),
        migrations.CreateModel(
            name='PantryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit', models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('tsp', 'tsp'), ('tbsp', 'tbsp'), ('item', 'item'), ('pack', 'pack')], max_length=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.ingredient')),
                ('meal_plan_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pantry_adjustments', to='recipes.mealplanentry')),
                ('pantry_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.pantryitem')),
            ],
            options={
                'ordering': ['ingredient__name', 'unit', 'created_at'],
            },
        ),
    ]
