# Generated by Django 4.2.30 on 2026-06-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_meal_plan_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='enabled_slots',
            field=models.JSONField(default=list),
        ),
    ]
