# Generated by Django 4.2.30 on 2026-06-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_appsetting_enabled_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='group_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
