# Generated by Django 4.2.30 on 2026-06-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_add_recipeingredient_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='theme',
            field=models.CharField(choices=[('system', 'System'), ('light', 'Light'), ('dark', 'Dark')], default='system', max_length=10),
        ),
    ]
