# Generated by Django 4.2.30 on 2026-06-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_appsetting_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsetting',
            name='theme',
        ),
        migrations.AddField(
            model_name='appsetting',
            name='accent_color',
            field=models.CharField(choices=[('green', 'Green'), ('teal', 'Teal'), ('blue', 'Blue'), ('purple', 'Purple'), ('pink', 'Pink')], default='green', max_length=20),
        ),
    ]
