# Generated by Django 4.2.30 on 2026-06-14 18:24

from django.db import migrations, models
import django.db.models.deletion


def migrate_ingredient_categories(apps, schema_editor):
    Ingredient = apps.get_model("recipes", "Ingredient")
    IngredientCategory = apps.get_model("recipes", "IngredientCategory")
    created = {}
    for ingredient in Ingredient.objects.exclude(category_text="").iterator():
        cat_name = " ".join(ingredient.category_text.strip().split())
        if not cat_name:
            continue
        if cat_name not in created:
            category, _ = IngredientCategory.objects.get_or_create(name=cat_name)
            created[cat_name] = category
        ingredient.category = created[cat_name]
        ingredient.save(update_fields=["category"])


def seed_default_categories(apps, schema_editor):
    IngredientCategory = apps.get_model("recipes", "IngredientCategory")
    defaults = [
        "Fruit & Vegetables",
        "Meat & Poultry",
        "Fish & Seafood",
        "Dairy & Eggs",
        "Bakery",
        "Pantry",
        "Pasta & Rice",
        "Spices & Seasonings",
        "Oils & Vinegars",
        "Sauces & Condiments",
        "Frozen",
        "Beverages",
        "Fresh Herbs",
        "Nuts & Seeds",
        "Baking Supplies",
        "Deli",
        "Other",
    ]
    for idx, name in enumerate(defaults):
        IngredientCategory.objects.get_or_create(name=name, defaults={"order": idx})


def seed_default_normalizations(apps, schema_editor):
    IngredientNormalization = apps.get_model("recipes", "IngredientNormalization")
    entries = [
        ("plain flour", "all-purpose flour"),
        ("all purpose flour", "all-purpose flour"),
        ("self raising flour", "self-raising flour"),
        ("self rising flour", "self-raising flour"),
        ("strong white flour", "bread flour"),
        ("powdered sugar", "icing sugar"),
        ("confectioners sugar", "icing sugar"),
        ("confectioner's sugar", "icing sugar"),
        ("table salt", "salt"),
        ("sea salt", "salt"),
        ("kosher salt", "salt"),
        ("cooking salt", "salt"),
        ("unsalted butter", "butter"),
        ("salted butter", "butter"),
        ("canola oil", "vegetable oil"),
        ("rapeseed oil", "vegetable oil"),
        ("extra virgin olive oil", "olive oil"),
        ("virgin olive oil", "olive oil"),
        ("heavy cream", "double cream"),
        ("whipping cream", "double cream"),
        ("heavy whipping cream", "double cream"),
        ("whole wheat flour", "wholemeal flour"),
        ("whole-wheat flour", "wholemeal flour"),
        ("cooking oil", "vegetable oil"),
        ("spring onion", "spring onion"),
        ("green onion", "spring onion"),
        ("scallion", "spring onion"),
        ("scallions", "spring onion"),
        ("spring onions", "spring onion"),
        ("green onions", "spring onion"),
        ("coriander", "coriander"),
        ("cilantro", "coriander"),
        ("caster sugar", "caster sugar"),
        ("superfine sugar", "caster sugar"),
        ("granulated sugar", "granulated sugar"),
        ("white sugar", "granulated sugar"),
        ("brown sugar", "brown sugar"),
        ("light brown sugar", "brown sugar"),
        ("dark brown sugar", "dark brown sugar"),
        ("icing sugar", "icing sugar"),
        ("confectioners' sugar", "icing sugar"),
        ("bicarbonate of soda", "baking soda"),
        ("bicarb", "baking soda"),
        ("baking powder", "baking powder"),
        ("cornstarch", "cornflour"),
        ("corn starch", "cornflour"),
        ("corn flour", "cornflour"),
        ("golden syrup", "golden syrup"),
        ("maple syrup", "maple syrup"),
        ("honey", "honey"),
        ("egg", "egg"),
        ("eggs", "egg"),
        ("large egg", "egg"),
        ("large eggs", "egg"),
        ("free-range egg", "egg"),
        ("free-range eggs", "egg"),
        ("garlic clove", "garlic"),
        ("garlic cloves", "garlic"),
    ]
    for match, canonical in entries:
        IngredientNormalization.objects.get_or_create(
            match_pattern=match,
            defaults={"canonical_name": canonical},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_accent_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'ingredient categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IngredientNormalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_pattern', models.CharField(help_text="Raw ingredient text to match, e.g. 'plain flour'", max_length=200, unique=True)),
                ('canonical_name', models.CharField(db_index=True, help_text="Canonical ingredient name, e.g. 'all-purpose flour'", max_length=200)),
            ],
            options={
                'ordering': ['match_pattern'],
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='canonical',
            field=models.ForeignKey(blank=True, help_text='Canonical ingredient for shopping list grouping.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='recipes.ingredient'),
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='category',
            new_name='category_text',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Supermarket section, such as Fruit & veg or Bakery.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.ingredientcategory'),
        ),
        migrations.RunPython(migrate_ingredient_categories, migrations.RunPython.noop),
        migrations.RunPython(seed_default_categories, migrations.RunPython.noop),
        migrations.RunPython(seed_default_normalizations, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='ingredient',
            name='category_text',
        ),
        migrations.AlterField(
            model_name='pantryadjustment',
            name='unit',
            field=models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('tsp', 'tsp'), ('tbsp', 'tbsp'), ('cup', 'cup'), ('clove', 'clove'), ('pinch', 'pinch'), ('slice', 'slice'), ('piece', 'piece'), ('head', 'head'), ('bunch', 'bunch'), ('stalk', 'stalk'), ('item', 'item'), ('pack', 'pack')], max_length=8),
        ),
        migrations.AlterField(
            model_name='pantryitem',
            name='unit',
            field=models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('tsp', 'tsp'), ('tbsp', 'tbsp'), ('cup', 'cup'), ('clove', 'clove'), ('pinch', 'pinch'), ('slice', 'slice'), ('piece', 'piece'), ('head', 'head'), ('bunch', 'bunch'), ('stalk', 'stalk'), ('item', 'item'), ('pack', 'pack')], max_length=8),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('tsp', 'tsp'), ('tbsp', 'tbsp'), ('cup', 'cup'), ('clove', 'clove'), ('pinch', 'pinch'), ('slice', 'slice'), ('piece', 'piece'), ('head', 'head'), ('bunch', 'bunch'), ('stalk', 'stalk'), ('item', 'item'), ('pack', 'pack')], max_length=8),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='pantry_used_unit',
            field=models.CharField(blank=True, choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('tsp', 'tsp'), ('tbsp', 'tbsp'), ('cup', 'cup'), ('clove', 'clove'), ('pinch', 'pinch'), ('slice', 'slice'), ('piece', 'piece'), ('head', 'head'), ('bunch', 'bunch'), ('stalk', 'stalk'), ('item', 'item'), ('pack', 'pack')], max_length=8),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='unit',
            field=models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('tsp', 'tsp'), ('tbsp', 'tbsp'), ('cup', 'cup'), ('clove', 'clove'), ('pinch', 'pinch'), ('slice', 'slice'), ('piece', 'piece'), ('head', 'head'), ('bunch', 'bunch'), ('stalk', 'stalk'), ('item', 'item'), ('pack', 'pack')], max_length=8),
        ),
    ]
