# Generated by Django 4.2.30 on 2026-06-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_ingredientcategory_ingredientnormalization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantryadjustment',
            name='unit',
            field=models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('tsp', 'tsp'), ('tbsp', 'tbsp'), ('cup', 'cup'), ('clove', 'clove'), ('pinch', 'pinch'), ('slice', 'slice'), ('piece', 'piece'), ('head', 'head'), ('bunch', 'bunch'), ('stalk', 'stalk'), ('item', 'item'), ('pack', 'pack'), ('lb', 'lb'), ('oz', 'oz')], max_length=8),
        ),
        migrations.AlterField(
            model_name='pantryitem',
            name='unit',
            field=models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('tsp', 'tsp'), ('tbsp', 'tbsp'), ('cup', 'cup'), ('clove', 'clove'), ('pinch', 'pinch'), ('slice', 'slice'), ('piece', 'piece'), ('head', 'head'), ('bunch', 'bunch'), ('stalk', 'stalk'), ('item', 'item'), ('pack', 'pack'), ('lb', 'lb'), ('oz', 'oz')], max_length=8),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('tsp', 'tsp'), ('tbsp', 'tbsp'), ('cup', 'cup'), ('clove', 'clove'), ('pinch', 'pinch'), ('slice', 'slice'), ('piece', 'piece'), ('head', 'head'), ('bunch', 'bunch'), ('stalk', 'stalk'), ('item', 'item'), ('pack', 'pack'), ('lb', 'lb'), ('oz', 'oz')], max_length=8),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='pantry_used_unit',
            field=models.CharField(blank=True, choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('tsp', 'tsp'), ('tbsp', 'tbsp'), ('cup', 'cup'), ('clove', 'clove'), ('pinch', 'pinch'), ('slice', 'slice'), ('piece', 'piece'), ('head', 'head'), ('bunch', 'bunch'), ('stalk', 'stalk'), ('item', 'item'), ('pack', 'pack'), ('lb', 'lb'), ('oz', 'oz')], max_length=8),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='unit',
            field=models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('tsp', 'tsp'), ('tbsp', 'tbsp'), ('cup', 'cup'), ('clove', 'clove'), ('pinch', 'pinch'), ('slice', 'slice'), ('piece', 'piece'), ('head', 'head'), ('bunch', 'bunch'), ('stalk', 'stalk'), ('item', 'item'), ('pack', 'pack'), ('lb', 'lb'), ('oz', 'oz')], max_length=8),
        ),
    ]
