"""
Ingredient keyword-to-category mapping for auto-categorisation.

CATEGORY_KEYWORDS maps canonical category names to lists of lowercase,
singular-form keyword patterns.  Keywords are ordered by priority (more
specific first).  When an ingredient name contains multiple keywords the
first match wins, so ordering matters.

Near-duplicate categories from the database are handled as comments so
the matching code can route them to the canonical category:

  Condiments        -> Sauces & Condiments
  Oils              -> Oils & Vinegars
  Pasta             -> Pasta & Rice
  Tins              -> Pantry
  Vegetables        -> Fruit & Vegetables

The "Other" category has an empty list and acts as the fallback when no
keyword matches.
"""

CATEGORY_KEYWORDS = {
    # ------------------------------------------------------------------
    # Fruit & Vegetables  (also matches the old "Vegetables" category)
    # ------------------------------------------------------------------
    "Fruit & Vegetables": [
        # Fruits (specific varieties first, then generic)
        "grapefruit",
        "passionfruit",
        "passion fruit",
        "dragon fruit",
        "star fruit",
        "jackfruit",
        "breadfruit",
        "kiwifruit",
        "honeydew melon",
        "cantaloupe",
        "watermelon",
        "rockmelon",
        "blood orange",
        "mandarin",
        "clementine",
        "tangerine",
        "satsuma",
        "pomelo",
        "ugli fruit",
        "key lime",
        "meyer lemon",
        "crabapple",
        "custard apple",
        "pineapple",
        "strawberry",
        "blueberry",
        "raspberry",
        "blackberry",
        "boysenberry",
        "cranberry",
        "gooseberry",
        "elderberry",
        "mulberry",
        "loganberry",
        "cloudberry",
        "lingonberry",
        "bilberry",
        "huckleberry",
        "currant",
        "blackcurrant",
        "redcurrant",
        "whitecurrant",
        "pomegranate",
        "persimmon",
        "kumquat",
        "loquat",
        "lychee",
        "rambutan",
        "mangosteen",
        "durian",
        "guava",
        "papaya",
        "pawpaw",
        "nectarine",
        "peach",
        "apricot",
        "plum",
        "damson",
        "greengage",
        "mango",
        "cherry",
        "sour cherry",
        "morello cherry",
        "grape",
        "raisin",
        "sultana",
        "prune",
        "fig",
        "date",
        "medjool date",
        "olive",
        "avocado",
        "coconut",
        "rhubarb",
        "quince",
        "tamarind",
        "plantain",
        "feijoa",
        "pepino",
        "tamarillo",
        "apple",
        "pear",
        "nashi pear",
        "asian pear",
        "banana",
        "orange",
        "lemon",
        "lime",
        "fruit",
        # Berries and small fruit
        "mixed berry",
        "frozen berry",
        "dried fruit",
        "dried apple",
        "dried apricot",
        "dried cranberry",
        "dried fig",
        "dried mango",
        "dried prune",
        "dried pear",
        "dried peach",
        "dried pineapple",
        "dried banana",
        "candied peel",
        "glace cherry",
        "fruit juice",
        "lemon juice",
        "lime juice",
        "orange juice",
        "apple juice",
        "lemon zest",
        "lime zest",
        "orange zest",

        # Vegetables (specific varieties first)
        "sweet potato",
        "kumara",
        "bell pepper",
        "capsicum",
        "red pepper",
        "green pepper",
        "yellow pepper",
        "orange pepper",
        "chilli pepper",
        "chili pepper",
        "jalapeno",
        "habanero",
        "serrano pepper",
        "poblano pepper",
        "anaheim pepper",
        "banana pepper",
        "cherry pepper",
        "romano pepper",
        "pepperoncini",
        "bird eye chilli",
        "scotch bonnet",
        "brussels sprout",
        "bok choy",
        "pak choi",
        "chinese cabbage",
        "napa cabbage",
        "savoy cabbage",
        "red cabbage",
        "white cabbage",
        "pointed cabbage",
        "spring greens",
        "collard green",
        "mustard green",
        "turnip green",
        "beetroot",
        "silverbeet",
        "chard",
        "swiss chard",
        "rainbow chard",
        "butternut squash",
        "acorn squash",
        "spaghetti squash",
        "gem squash",
        "pattypan squash",
        "kabocha",
        "courgette",
        "zucchini",
        "aubergine",
        "eggplant",
        "cauliflower",
        "broccoli",
        "broccolini",
        "tenderstem broccoli",
        "romanesco",
        "asparagus",
        "artichoke",
        "jerusalem artichoke",
        "globe artichoke",
        "fennel bulb",
        "celery",
        "celeriac",
        "kohlrabi",
        "radish",
        "daikon radish",
        "mooli",
        "turnip",
        "swede",
        "rutabaga",
        "parsnip",
        "carrot",
        "baby carrot",
        "mushroom",
        "button mushroom",
        "chestnut mushroom",
        "portobello mushroom",
        "portabella mushroom",
        "shitake mushroom",
        "shiitake",
        "oyster mushroom",
        "enoki mushroom",
        "porcini",
        "chanterelle",
        "morel",
        "ceps",
        "truffle",
        "spinach",
        "baby spinach",
        "kale",
        "cavolo nero",
        "curly kale",
        "lettuce",
        "romaine lettuce",
        "cos lettuce",
        "iceberg lettuce",
        "gem lettuce",
        "little gem",
        "butter lettuce",
        "round lettuce",
        "oak leaf lettuce",
        "lamb lettuce",
        "lambs lettuce",
        "watercress",
        "rocket",
        "arugula",
        "endive",
        "chicory",
        "radicchio",
        "witloof",
        "frisee",
        "mizuna",
        "tatsoi",
        "corn salad",
        "mustard cress",
        "garden cress",
        "microgreen",
        "cucumber",
        "lebanese cucumber",
        "telegraph cucumber",
        "gherkin",
        "tomato",
        "cherry tomato",
        "plum tomato",
        "roma tomato",
        "beef tomato",
        "vine tomato",
        "heirloom tomato",
        "green tomato",
        "tomatillo",
        "onion",
        "red onion",
        "white onion",
        "brown onion",
        "yellow onion",
        "shallot",
        "spring onion",
        "scallion",
        "green onion",
        "leek",
        "garlic",
        "garlic clove",
        "roasted garlic",
        "black garlic",
        "garlic bulb",
        "ginger",
        "fresh ginger",
        "galangal",
        "turmeric root",
        "fresh turmeric",
        "potato",
        "new potato",
        "baby potato",
        "maris piper",
        "king edward",
        "desiree potato",
        "russet potato",
        "yukon gold",
        "red potato",
        "waxy potato",
        "floury potato",
        "jacket potato",
        "mashed potato",
        "pea",
        "garden pea",
        "petit pois",
        "mangetout",
        "snow pea",
        "sugar snap pea",
        "mushy pea",
        "green bean",
        "french bean",
        "runner bean",
        "broad bean",
        "fava bean",
        "edamame",
        "soybean",
        "bean sprout",
        "alfalfa sprout",
        "okra",
        "ladies finger",
        "bamboo shoot",
        "water chestnut",
        "palm heart",
        "heart of palm",
        "corn",
        "sweetcorn",
        "corn on the cob",
        "baby corn",
        "popcorn",
        "pumpkin",
        "squash",
        "marrow",
        "gourd",
        "bottle gourd",
        "bitter gourd",
        "bitter melon",
        "chayote",
        "christophene",
        "jicama",
        "yam",
        "taro",
        "cassava",
        "yucca",
        "purslane",
        "sorrel",
        "samphire",
        "sea beet",
        "sea kale",
        "nettle",
        "dandelion green",
        "beet leaf",
        "vegetable",
        "root vegetable",
        "mixed vegetable",
        "salad leaf",
        "salad green",
        "mixed leaf",
        "mixed salad",
        "bagged salad",
        "coleslaw mix",
        "stir fry vegetable",
        "soup vegetable",
        "vegetable stock",
    ],

    # ------------------------------------------------------------------
    # Meat & Poultry
    # ------------------------------------------------------------------
    "Meat & Poultry": [
        # Beef (specific cuts first)
        "beef fillet",
        "beef tenderloin",
        "filet mignon",
        "beef sirloin",
        "beef ribeye",
        "ribeye steak",
        "beef rump",
        "rump steak",
        "beef brisket",
        "beef chuck",
        "chuck steak",
        "beef shin",
        "beef shank",
        "beef short rib",
        "beef flank",
        "beef skirt",
        "skirt steak",
        "beef topside",
        "beef silverside",
        "beef bavette",
        "flat iron steak",
        "hanger steak",
        "onglet",
        "beef cheek",
        "ox cheek",
        "oxtail",
        "beef tongue",
        "ox tongue",
        "beef liver",
        "calves liver",
        "beef kidney",
        "ox kidney",
        "beef heart",
        "ox heart",
        "beef tripe",
        "beef mince",
        "ground beef",
        "minced beef",
        "beef steak",
        "steak",
        "beef joint",
        "roast beef",
        "beef dripping",
        "beef suet",
        "corned beef",
        "beef sausage",
        "beef burger",
        "beef patty",
        "beef meatball",
        "beef jerky",
        "bresaola",
        "beef stock",
        "beef broth",
        "beef gravy",
        "beef",

        # Pork (specific cuts first)
        "pork tenderloin",
        "pork fillet",
        "pork loin",
        "pork chop",
        "pork belly",
        "pork shoulder",
        "pork butt",
        "pork leg",
        "pork hock",
        "pork knuckle",
        "pork rib",
        "baby back rib",
        "spare rib",
        "pork mince",
        "ground pork",
        "minced pork",
        "pork sausage",
        "pork meatball",
        "pork scratchings",
        "crackling",
        "pork fat",
        "lard",
        "pancetta",
        "guanciale",
        "pork",

        # Bacon, Ham, Gammon
        "smoked bacon",
        "unsmoked bacon",
        "back bacon",
        "streaky bacon",
        "bacon rasher",
        "bacon lardon",
        "lardon",
        "pancetta",
        "cooked ham",
        "smoked ham",
        "honey ham",
        "prosciutto",
        "parma ham",
        "serrano ham",
        "iberico ham",
        "jamón",
        "speck",
        "gammon",
        "gammon joint",
        "gammon steak",
        "bacon",

        # Lamb
        "lamb chop",
        "lamb cutlet",
        "lamb shank",
        "lamb rack",
        "rack of lamb",
        "lamb leg",
        "leg of lamb",
        "lamb shoulder",
        "shoulder of lamb",
        "lamb loin",
        "lamb neck",
        "lamb breast",
        "lamb mince",
        "ground lamb",
        "minced lamb",
        "lamb kidney",
        "lamb liver",
        "lamb heart",
        "lamb sweetbread",
        "lamb sausage",
        "merguez",
        "lamb",

        # Veal
        "veal chop",
        "veal cutlet",
        "veal escalope",
        "veal shank",
        "osso buco",
        "veal mince",
        "ground veal",
        "veal",

        # Poultry
        "chicken breast",
        "chicken thigh",
        "chicken drumstick",
        "chicken leg",
        "chicken wing",
        "chicken tenderloin",
        "chicken fillet",
        "chicken mince",
        "ground chicken",
        "minced chicken",
        "chicken liver",
        "chicken heart",
        "chicken gizzard",
        "chicken sausage",
        "chicken meatball",
        "whole chicken",
        "roast chicken",
        "chicken stock",
        "chicken broth",
        "chicken gravy",
        "chicken skin",
        "chicken fat",
        "schmaltz",
        "poussin",
        "cornish hen",
        "capon",
        "chicken",

        # Turkey
        "turkey breast",
        "turkey leg",
        "turkey mince",
        "ground turkey",
        "turkey sausage",
        "turkey bacon",
        "whole turkey",
        "turkey crown",
        "turkey",

        # Duck
        "duck breast",
        "duck leg",
        "duck confit",
        "duck fat",
        "duck liver",
        "foie gras",
        "whole duck",
        "crispy duck",
        "peking duck",
        "duck",

        # Goose
        "goose breast",
        "goose leg",
        "goose fat",
        "whole goose",
        "goose",

        # Game & Other
        "venison",
        "venison steak",
        "venison haunch",
        "venison sausage",
        "rabbit",
        "rabbit leg",
        "wild rabbit",
        "hare",
        "jugged hare",
        "quail",
        "quail egg",
        "pheasant",
        "guinea fowl",
        "partridge",
        "pigeon",
        "wood pigeon",
        "squab",
        "grouse",
        "wild boar",
        "boar",
        "kangaroo",
        "ostrich",
        "goat",
        "goat meat",
        "kid",
        "mutton",
        "horse",
        "frog leg",
        "snail",
        "escargot",

        # Processed / Cured Meats
        "salami",
        "pepperoni",
        "chorizo",
        "sobrassada",
        "nduja",
        "mortadella",
        "bologna",
        "luncheon meat",
        "liverwurst",
        "braunschweiger",
        "black pudding",
        "blood sausage",
        "white pudding",
        "haggis",
        "boudin",
        "boudin noir",
        "andouille",
        "andouillette",
        "kielbasa",
        "bratwurst",
        "frankfurter",
        "hot dog",
        "wiener",
        "chipolata",
        "cumberland sausage",
        "toulouse sausage",
        "linguica",
        "longaniza",
        "boerewors",
        "breakfast sausage",
        "lamb merguez",
        "pork sausage",
        "smoked sausage",
        "garlic sausage",
        "italian sausage",
        "spicy sausage",
        "sausage",
        "sausage meat",
        "sausagemeat",
        "saveloy",
        "meat",
        "mince",
        "ground meat",
        "deli meat",
        "cold cut",
        "charcuterie",
        "pâté",
        "pate",
        "terrine",
    ],

    # ------------------------------------------------------------------
    # Fish & Seafood
    # ------------------------------------------------------------------
    "Fish & Seafood": [
        # White fish
        "cod",
        "cod fillet",
        "cod loin",
        "salt cod",
        "bacalao",
        "bacalhau",
        "haddock",
        "smoked haddock",
        "finnan haddie",
        "arbroath smokie",
        "halibut",
        "halibut fillet",
        "plaice",
        "plaice fillet",
        "sole",
        "dover sole",
        "lemon sole",
        "flounder",
        "turbot",
        "brill",
        "monkfish",
        "monkfish tail",
        "john dory",
        "gurnard",
        "pollock",
        "pollack",
        "hake",
        "whiting",
        "coley",
        "saithe",
        "tilapia",
        "pangasius",
        "basa",
        "catfish",
        "carp",
        "pike",
        "perch",
        "nile perch",
        "walleye",
        "mullet",
        "red mullet",
        "grey mullet",
        "sea bream",
        "gilt head bream",
        "dorade",
        "snapper",
        "red snapper",
        "barramundi",
        "grouper",
        "rockfish",
        "orange roughy",
        "escolar",
        "butterfish",
        "skate",
        "skate wing",
        "ray wing",
        "eel",
        "conger eel",
        "smoked eel",
        "jellied eel",
        "elver",
        "lamprey",
        "hagfish",
        "whitebait",
        "white fish",
        "fish fillet",

        # Oily fish
        "salmon",
        "salmon fillet",
        "salmon steak",
        "wild salmon",
        "atlantic salmon",
        "pacific salmon",
        "sockeye salmon",
        "coho salmon",
        "chinook salmon",
        "king salmon",
        "salmon trout",
        "salmon belly",
        "smoked salmon",
        "gravlax",
        "gravadlax",
        "lox",
        "trout",
        "trout fillet",
        "rainbow trout",
        "brown trout",
        "sea trout",
        "smoked trout",
        "arctic char",
        "char",
        "tuna",
        "tuna steak",
        "tuna loin",
        "yellowfin tuna",
        "ahi tuna",
        "albacore tuna",
        "bluefin tuna",
        "skipjack tuna",
        "bonito",
        "tinned tuna",
        "canned tuna",
        "mackerel",
        "mackerel fillet",
        "spanish mackerel",
        "king mackerel",
        "smoked mackerel",
        "horse mackerel",
        "jack mackerel",
        "sardine",
        "fresh sardine",
        "tinned sardine",
        "canned sardine",
        "pilchard",
        "anchovy",
        "anchovy fillet",
        "tinned anchovy",
        "canned anchovy",
        "boquerones",
        "herring",
        "kipper",
        "bloater",
        "pickled herring",
        "rollmop",
        "soused herring",
        "smelt",
        "sprat",
        "brisling",

        # Large / prime fish
        "swordfish",
        "swordfish steak",
        "marlin",
        "sailfish",
        "mahi mahi",
        "dorado",
        "kingfish",
        "yellowtail",
        "amberjack",
        "wahoo",
        "pompano",
        "black cod",
        "sablefish",

        # Shellfish
        "shrimp",
        "king prawn",
        "tiger prawn",
        "prawn",
        "langoustine",
        "dublin bay prawn",
        "scampi",
        "crayfish",
        "crawfish",
        "yabby",
        "lobster",
        "lobster tail",
        "spiny lobster",
        "crab",
        "crab meat",
        "crab claw",
        "crab leg",
        "brown crab",
        "blue crab",
        "soft shell crab",
        "spider crab",
        "king crab",
        "snow crab",
        "dungeness crab",
        "scallop",
        "king scallop",
        "queen scallop",
        "scallop roe",
        "mussel",
        "green lipped mussel",
        "oyster",
        "pacific oyster",
        "native oyster",
        "rock oyster",
        "clam",
        "littleneck clam",
        "manila clam",
        "razor clam",
        "geoduck",
        "cockle",
        "whelk",
        "winkle",
        "periwinkle",
        "abalone",
        "paua",
        "sea urchin",
        "uni",

        # Cephalopods
        "squid",
        "squid ring",
        "squid tube",
        "baby squid",
        "calamari",
        "octopus",
        "baby octopus",
        "cuttlefish",
        "cuttlefish ink",
        "squid ink",

        # Roe & Caviar
        "caviar",
        "salmon roe",
        "ikura",
        "trout roe",
        "lumpfish roe",
        "flying fish roe",
        "tobiko",
        "capelin roe",
        "masago",
        "tarako",
        "mentaiko",
        "bottarga",
        "mullet roe",
        "fish roe",
        "roe",

        # Processed / Surimi
        "fish cake",
        "fish ball",
        "fish finger",
        "fish stick",
        "seafood stick",
        "crab stick",
        "surimi",
        "kamaboko",
        "chikuwa",
        "fish paste",
        "dried shrimp",
        "dried fish",
        "fish sauce",
        "fish stock",
        "fumet",
        "dashi",

        # General
        "seafood",
        "shellfish",
        "mixed seafood",
        "fruits de mer",
        "seafood mix",
        "fish",
    ],

    # ------------------------------------------------------------------
    # Dairy & Eggs
    # ------------------------------------------------------------------
    "Dairy & Eggs": [
        # Milk & Cream
        "whole milk",
        "semi skimmed milk",
        "skimmed milk",
        "skim milk",
        "full fat milk",
        "full cream milk",
        "low fat milk",
        "fat free milk",
        "lactose free milk",
        "uht milk",
        "long life milk",
        "raw milk",
        "unpasteurised milk",
        "goat milk",
        "sheep milk",
        "buffalo milk",
        "buttermilk",
        "cultured buttermilk",
        "kefir",
        "ayran",
        "lassi",
        "sour milk",
        "double cream",
        "heavy cream",
        "whipping cream",
        "single cream",
        "light cream",
        "half and half",
        "clotted cream",
        "extra thick cream",
        "sour cream",
        "soured cream",
        "creme fraiche",
        "creme fraîche",
        "cooking cream",
        "long life cream",
        "sterilised cream",
        "aerosol cream",
        "squirty cream",
        "spray cream",
        "milk",
        "cream",

        # Condensed / Evaporated
        "evaporated milk",
        "condensed milk",
        "sweetened condensed milk",
        "carnation milk",

        # Yogurt / Fromage Blanc
        "greek yogurt",
        "greek yoghurt",
        "natural yogurt",
        "plain yogurt",
        "fruit yogurt",
        "drinking yogurt",
        "frozen yogurt",
        "soy yogurt",
        "coconut yogurt",
        "labneh",
        "skyr",
        "quark",
        "fromage frais",
        "fromage blanc",
        "petit suisse",
        "yogurt",
        "yoghurt",

        # Butter
        "unsalted butter",
        "salted butter",
        "clarified butter",
        "ghee",
        "cultured butter",
        "goat butter",
        "spreadable butter",
        "garlic butter",
        "herb butter",
        "beurre noisette",
        "brown butter",
        "butter",

        # Margarine & Spreads
        "margarine",
        "dairy spread",
        "butter substitute",
        "olive spread",
        "sunflower spread",
        "vegetable spread",

        # Cheese (soft)
        "cream cheese",
        "soft cheese",
        "philadelphia",
        "mascarpone",
        "ricotta",
        "cottage cheese",
        "paneer",
        "mozzarella",
        "buffalo mozzarella",
        "bocconcini",
        "burrata",
        "stracciatella",
        "scamorza",
        "feta",
        "halloumi",
        "grilling cheese",
        "goat cheese",
        "chevre",
        "chevre",
        "brie",
        "camembert",
        "st felicien",
        "coulommiers",
        "neufchatel",
        "fromage affine",
        "reblochon",
        "taleggio",
        "epoisses",
        "munster",
        "langres",
        "pont l eveque",
        "vacherin",
        "mont d or",
        "chaource",
        "brillat savarin",
        "delice de bourgogne",

        # Cheese (semi-hard / hard)
        "cheddar",
        "mature cheddar",
        "extra mature cheddar",
        "vintage cheddar",
        "red leicester",
        "double gloucester",
        "cheshire",
        "lancashire",
        "wensleydale",
        "caerphilly",
        "derby",
        "sage derby",
        "gouda",
        "edam",
        "maasdam",
        "leerdammer",
        "emmental",
        "emmenthal",
        "swiss cheese",
        "gruyere",
        "comte",
        "beaufort",
        "raclette",
        "appenzeller",
        "jarlsberg",
        "tilsit",
        "havarti",
        "fontina",
        "monterey jack",
        "pepper jack",
        "colby",
        "muenster",
        "provolone",
        "parmesan",
        "parmigiano reggiano",
        "grana padano",
        "pecorino",
        "pecorino romano",
        "manchego",
        "asiago",
        "aged gouda",
        "old amsterdam",

        # Blue cheese
        "stilton",
        "blue stilton",
        "roquefort",
        "gorgonzola",
        "dolcelatte",
        "danablu",
        "danish blue",
        "bleu d auvergne",
        "fourme d ambert",
        "cambozola",
        "shropshire blue",
        "cashel blue",
        "blue cheese",

        # Cheese (general)
        "cheese",
        "grated cheese",
        "shredded cheese",
        "cheese mix",
        "cheese blend",
        "cheese slice",
        "cheese spread",
        "cheese string",
        "babybel",
        "laughing cow",
        "dairylea",
        "processed cheese",
        "cheese curd",

        # Eggs
        "chicken egg",
        "free range egg",
        "organic egg",
        "duck egg",
        "goose egg",
        "quail egg",
        "ostrich egg",
        "egg white",
        "egg yolk",
        "liquid egg",
        "pasteurised egg",
        "egg substitute",
        "egg replacer",
        "powdered egg",
        "dried egg",
        "egg wash",
        "egg",

        # Whey / Casein
        "whey",
        "whey protein",
        "casein",
        "milk powder",
        "powdered milk",
        "skimmed milk powder",
        "dried skimmed milk",
        "malted milk powder",
        "dairy",
    ],

    # ------------------------------------------------------------------
    # Bakery
    # ------------------------------------------------------------------
    "Bakery": [
        # Bread (loaves)
        "sourdough",
        "sourdough bread",
        "white bread",
        "wholemeal bread",
        "whole wheat bread",
        "brown bread",
        "granary bread",
        "multigrain bread",
        "seeded bread",
        "rye bread",
        "pumpernickel",
        "soda bread",
        "irish soda bread",
        "cornbread",
        "brioche loaf",
        "milk bread",
        "hokkaido milk bread",
        "pain de mie",
        "challah",
        "ciabatta",
        "focaccia",
        "olive bread",
        "sun dried tomato bread",
        "cheese bread",
        "garlic bread",
        "garlic baguette",
        "baguette",
        "french stick",
        "bloomer",
        "tin loaf",
        "farmhouse loaf",
        "split tin",
        "batch loaf",
        "cottage loaf",
        "cob loaf",
        "bread roll",
        "dinner roll",
        "bread bun",
        "bap",
        "barm",
        "stottie",
        "morning roll",
        "soft roll",
        "crusty roll",
        "kaiser roll",
        "vienna roll",
        "hoagie roll",
        "sub roll",
        "hot dog roll",
        "hot dog bun",
        "burger bun",
        "brioche bun",
        "brioche roll",
        "bread",

        # Flatbreads
        "tortilla",
        "flour tortilla",
        "corn tortilla",
        "wheat tortilla",
        "wrap",
        "pitta",
        "pita",
        "pita bread",
        "naan",
        "naan bread",
        "garlic naan",
        "peshwari naan",
        "keema naan",
        "roti",
        "chapati",
        "chapatti",
        "paratha",
        "puri",
        "poori",
        "lavash",
        "matzo",
        "matzah",
        "flatbread",

        # Pastry / Enriched
        "croissant",
        "pain au chocolat",
        "chocolatine",
        "pain aux raisins",
        "danish pastry",
        "cinnamon roll",
        "cinnamon swirl",
        "brioche",
        "morning bun",
        "panettone",
        "stollen",
        "fruit loaf",
        "teacake",
        "hot cross bun",
        "bara brith",
        "barmbrack",
        "malt loaf",
        "soreen",

        # Baking staples (breadcrumb / panko)
        "breadcrumb",
        "panko",
        "bread crumb",
        "dried breadcrumb",
        "fresh breadcrumb",
        "golden breadcrumb",
        "japanese breadcrumb",
        "crouton",
        "breadstick",
        "grissini",
        "bread roll",

        # Scones / English muffins / Crumpets
        "english muffin",
        "crumpet",
        "muffin",
        "scone",
        "cheese scone",
        "fruit scone",
        "plain scone",
        "potato scone",
        "tattie scone",
        "griddle scone",
        "drop scone",
        "scotch pancake",
        "pikelet",
        "pancake",
        "crepe",
        "american pancake",
        "waffle",
        "blini",

        # Bagels / Pretzels
        "bagel",
        "plain bagel",
        "sesame bagel",
        "cinnamon raisin bagel",
        "everything bagel",
        "pretzel",
        "soft pretzel",
        "pretzel roll",
        "pretzel bun",

        # Crackers / Crispbread
        "cracker",
        "water biscuit",
        "cream cracker",
        "oatcake",
        "oat biscuit",
        "rice cake",
        "corn cake",
        "crispbread",
        "ryvita",
        "knackerbrod",
        "melba toast",
        "rusk",
        "zwieback",
        "breadstick",

        # Donuts / Doughnuts
        "doughnut",
        "donut",
        "ring donut",
        "jam doughnut",
        "custard doughnut",
        "filled doughnut",
        "sugar donut",

        # Pastry cases / Tarts (bakery)
        "pastry case",
        "tart case",
        "flan case",
        "vol au vent",
        "puff pastry shell",
        "filo cup",

        # Toasts / Rusks
        "toast",
        "white toast",
        "brown toast",
        "french toast",
        "eggy bread",
        "toast bread",

        # Bakery general
        "bakery",
        "baked good",
        "artisan bread",
        "fresh bread",
        "part baked bread",
        "part baked roll",
        "dough ball",
        "pizza base",
        "pizza dough",
    ],

    # ------------------------------------------------------------------
    # Pantry  (also matches old "Tins" category)
    # ------------------------------------------------------------------
    "Pantry": [
        # Rice
        "white rice",
        "long grain rice",
        "easy cook rice",
        "american rice",
        "brown rice",
        "wholegrain rice",
        "basmati rice",
        "jasmine rice",
        "thai fragrant rice",
        "sushi rice",
        "sticky rice",
        "glutinous rice",
        "risotto rice",
        "arborio rice",
        "arborio",
        "carnaroli rice",
        "vialone nano",
        "paella rice",
        "bomba rice",
        "wild rice",
        "black rice",
        "red rice",
        "red camargue rice",
        "short grain rice",
        "medium grain rice",
        "pudding rice",
        "broken rice",
        "parboiled rice",
        "converted rice",
        "golden vegetable rice",
        "savoury rice",
        "microwave rice",
        "boil in bag rice",
        "rice",

        # Grains / Cereals
        "couscous",
        "giant couscous",
        "israeli couscous",
        "maftoul",
        "bulgur wheat",
        "bulgur",
        "bulgar wheat",
        "quinoa",
        "red quinoa",
        "white quinoa",
        "black quinoa",
        "tricolor quinoa",
        "barley",
        "pearl barley",
        "pot barley",
        "barley flake",
        "farro",
        "spelt",
        "pearl spelt",
        "freekeh",
        "buckwheat",
        "kasha",
        "buckwheat groat",
        "millet",
        "amaranth",
        "teff",
        "sorghum",
        "cracked wheat",
        "wheat berry",
        "rye grain",
        "oat groat",
        "polenta",
        "cornmeal",
        "maize meal",
        "grits",
        "hominy",
        "semolina",
        "tapioca",
        "sago",
        "grain",
        "mixed grain",

        # Oats / Cereal
        "rolled oat",
        "porridge oat",
        "jumbo oat",
        "pinhead oatmeal",
        "steel cut oat",
        "oatmeal",
        "instant oat",
        "quick oat",
        "muesli",
        "granola",
        "cereal",
        "cornflake",
        "bran flake",
        "bran cereal",
        "wheat biscuit",
        "weetabix",
        "shredded wheat",
        "rice krispie",
        "puffed rice",
        "puffed wheat",
        "oat",

        # Bran & Germ
        "wheat bran",
        "oat bran",
        "wheat germ",
        "bran",

        # Dried legumes (pulses)
        "dried kidney bean",
        "dried cannellini bean",
        "dried butter bean",
        "dried chickpea",
        "dried lentil",
        "dried split pea",
        "dried black bean",
        "dried pinto bean",
        "dried lima bean",
        "dried navy bean",
        "dried haricot bean",
        "dried fava bean",
        "dried broad bean",
        "dried mung bean",
        "dried adzuki bean",
        "dried black eyed pea",
        "dried pea",
        "dried bean",
        "dried pulse",
        "dried legume",

        # Canned / Tinned legumes
        "canned kidney bean",
        "tinned kidney bean",
        "canned cannellini bean",
        "tinned cannellini bean",
        "canned chickpea",
        "tinned chickpea",
        "canned black bean",
        "tinned black bean",
        "canned butter bean",
        "tinned butter bean",
        "canned pinto bean",
        "canned baked bean",
        "tinned baked bean",
        "canned mixed bean",
        "tinned mixed bean",
        "baked bean",
        "kidney bean",
        "cannellini bean",
        "butter bean",
        "black bean",
        "pinto bean",
        "lima bean",
        "navy bean",
        "haricot bean",
        "fava bean",
        "broad bean",
        "mung bean",
        "adzuki bean",
        "black eyed pea",
        "black eye bean",
        "flageolet bean",
        "borlotti bean",
        "cranberry bean",
        "bean",

        # Lentils & Split peas
        "red lentil",
        "green lentil",
        "brown lentil",
        "puy lentil",
        "yellow lentil",
        "black lentil",
        "beluga lentil",
        "split pea",
        "yellow split pea",
        "green split pea",
        "chana dal",
        "urad dal",
        "toor dal",
        "masoor dal",
        "moong dal",
        "lentil",
        "dal",
        "chickpea",
        "garbanzo bean",
        "gram",
        "chana",

        # Canned / Tinned vegetables
        "canned tomato",
        "tinned tomato",
        "chopped tomato",
        "plum tomato canned",
        "crushed tomato",
        "passata",
        "sieved tomato",
        "canned sweetcorn",
        "tinned sweetcorn",
        "sweetcorn canned",
        "canned corn",
        "canned pea",
        "tinned pea",
        "mushy pea canned",
        "processed pea",
        "canned green bean",
        "tinned green bean",
        "canned carrot",
        "tinned carrot",
        "canned spinach",
        "canned asparagus",
        "canned artichoke",
        "tinned artichoke",
        "canned beetroot",
        "pickled beetroot",
        "tinned vegetable",
        "canned vegetable",
        "mixed vegetable canned",

        # Canned / Tinned fruit
        "canned peach",
        "tinned peach",
        "canned pear",
        "tinned pear",
        "canned pineapple",
        "tinned pineapple",
        "canned mandarin",
        "tinned mandarin",
        "canned apricot",
        "tinned apricot",
        "canned cherry",
        "canned fruit cocktail",
        "tinned fruit cocktail",
        "canned fruit",
        "tinned fruit",
        "fruit in syrup",
        "fruit in juice",
        "pie filling canned",

        # Canned / Tinned fish & meat
        "canned tuna",
        "tinned tuna",
        "canned salmon",
        "tinned salmon",
        "canned sardine",
        "tinned sardine",
        "canned mackerel",
        "tinned mackerel",
        "canned anchovy",
        "tinned anchovy",
        "canned crab",
        "tinned crab",
        "spam",
        "canned ham",
        "tinned ham",
        "canned meat",
        "tinned meat",
        "corned beef",
        "canned corned beef",

        # Canned soup & broth
        "canned soup",
        "tinned soup",
        "condensed soup",
        "cream of tomato soup",
        "cream of mushroom soup",
        "cream of chicken soup",
        "chicken soup canned",
        "vegetable soup canned",
        "oxtail soup canned",
        "minestrone canned",
        "broth canned",

        # Stock / Bouillon
        "vegetable stock",
        "vegetable stock cube",
        "vegetable stock pot",
        "vegetable bouillon",
        "chicken stock",
        "chicken stock cube",
        "chicken stock pot",
        "chicken bouillon",
        "beef stock",
        "beef stock cube",
        "beef stock pot",
        "beef bouillon",
        "fish stock",
        "fish stock cube",
        "fish stock pot",
        "fish bouillon",
        "lamb stock",
        "ham stock",
        "dashi powder",
        "dashi granule",
        "instant dashi",
        "stock cube",
        "stock pot",
        "bouillon",
        "bouillon cube",
        "broth powder",
        "stock",

        # Gravy
        "gravy granule",
        "gravy powder",
        "instant gravy",
        "bisto",
        "gravy browning",
        "onion gravy",
        "chicken gravy",
        "beef gravy",
        "gravy",

        # Jams / Preserves / Spreads
        "strawberry jam",
        "raspberry jam",
        "apricot jam",
        "marmalade",
        "orange marmalade",
        "lemon curd",
        "fruit preserve",
        "fruit spread",
        "apple butter",
        "mincemeat",
        "jam",

        # Syrup / Treacle / Molasses
        "golden syrup",
        "maple syrup",
        "honey",
        "manuka honey",
        "acacia honey",
        "runny honey",
        "set honey",
        "treacle",
        "black treacle",
        "molasses",
        "blackstrap molasses",
        "agave syrup",
        "agave nectar",
        "corn syrup",
        "light corn syrup",
        "dark corn syrup",
        "date syrup",
        "pomegranate molasses",
        "rice syrup",
        "malt extract",
        "barley malt syrup",
        "syrup",

        # Spreads (savoury)
        "marmite",
        "vegemite",
        "bovril",
        "promite",
        "yeast extract",
        "peanut butter",
        "crunchy peanut butter",
        "smooth peanut butter",
        "almond butter",
        "cashew butter",
        "sunflower seed butter",
        "tahini",
        "chocolate spread",
        "hazelnut spread",
        "nutella",
        "biscoff spread",
        "speculoos spread",

        # Pickles / Preserved vegetables
        "pickled onion",
        "pickled gherkin",
        "pickled cucumber",
        "dill pickle",
        "bread and butter pickle",
        "pickled beetroot",
        "pickled red cabbage",
        "pickled jalapeno",
        "pickled pepper",
        "pickled egg",
        "pickled walnut",
        "pickle",
        "chutney",
        "mango chutney",
        "lime pickle",
        "brinjal pickle",
        "piccalilli",
        "branston pickle",
        "relish",
        "sweet pickle",
        "cornichon",
        "gherkin",
        "caper",
        "caper berry",

        # Olives & antipasti
        "green olive",
        "black olive",
        "kalamata olive",
        "nicoise olive",
        "manzanilla olive",
        "gordal olive",
        "stuffed olive",
        "pitted olive",
        "sliced olive",
        "olive",

        # Sun-dried / preserved
        "sun dried tomato",
        "sundried tomato",
        "semi dried tomato",
        "roasted red pepper",
        "grilled pepper",
        "piquillo pepper",
        "artichoke heart",
        "chargrilled artichoke",
        "marinated artichoke",
        "palm heart",
        "heart of palm",
        "bamboo shoot",
        "water chestnut",

        # Tofu / Soy products
        "tofu",
        "silken tofu",
        "firm tofu",
        "extra firm tofu",
        "smoked tofu",
        "fried tofu",
        "tofu puff",
        "tempeh",
        "soy chunk",
        "soya chunk",
        "textured vegetable protein",
        "tvp",
        "seitan",

        # Coconut products
        "coconut milk",
        "coconut cream",
        "cream of coconut",
        "coconut water",
        "coconut milk powder",
        "creamed coconut",
        "coconut block",
        "desiccated coconut",
        "shredded coconut",
        "coconut flake",
        "coconut chip",
        "toasted coconut",

        # Noodles (dried / shelf-stable)
        "rice noodle",
        "rice vermicelli",
        "vermicelli noodle",
        "flat rice noodle",
        "pad thai noodle",
        "egg noodle",
        "dried egg noodle",
        "ramen noodle",
        "instant noodle",
        "pot noodle",
        "soba noodle",
        "udon noodle",
        "somen noodle",
        "glass noodle",
        "cellophane noodle",
        "sweet potato noodle",
        "shirataki noodle",
        "rice paper",
        "spring roll wrapper",
        "rice paper wrapper",
        "noodle",

        # Flour / Meal (non-baking specific)
        "cornflour",
        "corn starch",
        "cornstarch",
        "tapioca starch",
        "tapioca flour",
        "potato starch",
        "potato flour",
        "arrowroot",
        "arrowroot powder",
        "rice flour",
        "glutinous rice flour",
        "gram flour",
        "besan",
        "chickpea flour",
        "paneer flour",

        # Seasoning / Sauce packets
        "stir fry sauce",
        "curry sauce jar",
        "pasta sauce jar",
        "cooking sauce",
        "simmer sauce",
        "recipe mix",
        "flavour packet",
        "seasoning mix",
        "taco seasoning",
        "fajita seasoning",
        "chilli con carne mix",
        "spaghetti bolognese mix",
        "shepherd pie mix",
        "casserole mix",
        "soup mix",
        "dip mix",
        "gravy mix",

        # Dried herbs & spices (pre-jarred, refer to Spices & Seasonings too)
        # Placed here when seen as a general "pantry" purchase
        "mixed dried herb",
        "italian herb mix",
        "herbes de provence",

        # Gelatin / Jelly
        "jelly",
        "jelly cube",
        "jelly crystal",
        "jelly powder",
        "jelly tablet",
        "table jelly",
        "gelatin",
        "gelatine",
        "gelatine leaf",
        "gelatine powder",
        "agar agar",
        "vegetarian jelly",

        # Snack / Crisps
        "crisp",
        "potato crisp",
        "tortilla chip",
        "corn chip",
        "nacho chip",
        "pretzel snack",
        "popcorn",
        "popcorn kernel",
        "snack",

        # Other shelf stable
        "baked bean",
        "spaghetti hoops",
        "alphabetti spaghetti",
        "ravioli canned",
        "macaroni cheese canned",
        "beans and sausage",
        "sauerkraut",
        "kimchi",
        "canned",
        "tinned",
        "tin",
    ],

    # ------------------------------------------------------------------
    # Pasta & Rice  (also matches old "Pasta" category)
    # ------------------------------------------------------------------
    "Pasta & Rice": [
        # Long pasta
        "spaghetti",
        "spaghettini",
        "capellini",
        "angel hair pasta",
        "angel hair",
        "vermicelli",
        "bucatini",
        "linguine",
        "linguini",
        "fettuccine",
        "fettucine",
        "tagliatelle",
        "pappardelle",
        "mafaldine",
        "reginette",
        "tripoline",
        "bigoli",
        "bavette",
        "tonnarelli",
        "spaghetti alla chitarra",

        # Short pasta
        "penne",
        "penne rigate",
        "penne lisce",
        "rigatoni",
        "fusilli",
        "fusilli bucati",
        "rotini",
        "rotelle",
        "ruote",
        "farfalle",
        "farfalle tricolore",
        "bow tie pasta",
        "conchiglie",
        "conchiglioni",
        "pipe rigate",
        "orecchiette",
        "gnocchetti sardi",
        "malloreddus",
        "trofi",
        "trofie",
        "strozzapreti",
        "cavatappi",
        "cavatelli",
        "casarecce",
        "gemelli",
        "campanelle",
        "garganelli",
        "radiatori",
        "spirali",
        "tortiglioni",
        "mezze maniche",
        "sedanini",
        "paccheri",
        "calamarata",

        # Tube pasta
        "macaroni",
        "macaroni elbow",
        "elbow macaroni",
        "elbow pasta",
        "ditalini",
        "ditali",
        "ziti",
        "mezzi ziti",
        "tubetti",

        # Tiny / Soup pasta
        "orzo",
        "orzo pasta",
        "risoni",
        "stelline",
        "alfabeto",
        "pastina",
        "acini di pepe",
        "fregola",
        "fregula",
        "couscous pasta",
        "pearl pasta",

        # Sheet / Stuffed pasta
        "lasagne",
        "lasagne sheet",
        "lasagna",
        "oven ready lasagne",
        "fresh lasagne sheet",
        "cannelloni",
        "cannelloni tube",
        "manicotti",
        "ravioli",
        "fresh ravioli",
        "spinach ravioli",
        "meat ravioli",
        "cheese ravioli",
        "tortellini",
        "fresh tortellini",
        "tortelloni",
        "cappelletti",
        "agnolotti",
        "mezzelune",
        "pansotti",
        "sorrentinos",

        # Speciality pasta
        "gnocchi",
        "potato gnocchi",
        "semolina gnocchi",
        "gnocchi alla romana",
        "spaetzle",
        "spatzle",
        "passatelli",
        "cencioni",
        "testaroli",

        # Egg / Fresh pasta
        "egg pasta",
        "fresh pasta",
        "fresh egg pasta",
        "fresh fettuccine",
        "fresh linguine",
        "fresh tagliatelle",

        # Wholewheat / Alternative pasta
        "wholewheat pasta",
        "wholemeal pasta",
        "brown pasta",
        "gluten free pasta",
        "corn pasta",
        "rice pasta",
        "lentil pasta",
        "chickpea pasta",
        "pea pasta",
        "edamame pasta",
        "quinoa pasta",
        "spelt pasta",
        "buckwheat pasta",
        "black bean pasta",
        "soba",
        "soba noodle",
        "udon",
        "udon noodle",
        "ramen",
        "ramen noodle",
        "naengmyeon",

        # General
        "pasta",
        "pasta shape",
        "mixed pasta",
        "pasta mix",
        "tricolour pasta",
        "coloured pasta",
        "flavoured pasta",
        "spinach pasta",
        "tomato pasta",
        "squid ink pasta",
        "dried pasta",
        "pasta shell",
        "pasta tube",
        "filled pasta",
        "stuffed pasta",
    ],

    # ------------------------------------------------------------------
    # Spices & Seasonings
    # ------------------------------------------------------------------
    "Spices & Seasonings": [
        # Salt
        "sea salt",
        "sea salt flake",
        "maldon salt",
        "fleur de sel",
        "sel gris",
        "kosher salt",
        "rock salt",
        "pink himalayan salt",
        "himalayan salt",
        "black salt",
        "kala namak",
        "smoked salt",
        "celery salt",
        "garlic salt",
        "onion salt",
        "seasoned salt",
        "table salt",
        "cooking salt",
        "flake salt",
        "coarse salt",
        "fine salt",
        "salt",

        # Pepper
        "black pepper",
        "black peppercorn",
        "tellicherry pepper",
        "white pepper",
        "white peppercorn",
        "green peppercorn",
        "pink peppercorn",
        "szechuan pepper",
        "sichuan pepper",
        "szechuan peppercorn",
        "timur pepper",
        "long pepper",
        "cubeb pepper",
        "grains of paradise",
        "cracked black pepper",
        "coarse black pepper",
        "ground black pepper",
        "ground white pepper",
        "pepper",

        # Chilli
        "chilli powder",
        "chili powder",
        "cayenne pepper",
        "cayenne",
        "chilli flake",
        "chili flake",
        "crushed chilli",
        "dried chilli",
        "dried chili",
        "aleppo pepper",
        "pul biber",
        "gochugaru",
        "korean chilli flake",
        "chipotle powder",
        "smoked chilli powder",
        "ancho chilli powder",
        "paprika",
        "smoked paprika",
        "sweet paprika",
        "hot paprika",
        "pimenton",
        "pimenton de la vera",
        "piment d espelette",
        "espelette pepper",
        "urfa biber",
        "urfa chilli",
        "sichuan chilli",
        "kashmiri chilli",
        "kashmiri chilli powder",
        "bird eye chilli dried",
        "dried chilli flake",
        "chilli",

        # Cumin / Coriander
        "cumin seed",
        "cumin",
        "ground cumin",
        "black cumin",
        "kala jeera",
        "nigella seed",
        "kalonji",
        "coriander seed",
        "ground coriander",
        "coriander",

        # Turmeric / Ginger
        "turmeric",
        "ground turmeric",
        "fresh turmeric",
        "ginger powder",
        "ground ginger",
        "dried ginger",

        # Cinnamon / Nutmeg / Clove / Allspice
        "cinnamon",
        "cinnamon stick",
        "cassia bark",
        "cinnamon bark",
        "ground cinnamon",
        "cinnamon powder",
        "nutmeg",
        "whole nutmeg",
        "ground nutmeg",
        "mace",
        "mace blade",
        "ground mace",
        "clove",
        "whole clove",
        "ground clove",
        "clove powder",
        "allspice",
        "allspice berry",
        "ground allspice",
        "pimento",
        "pimento berry",

        # Cardamom
        "cardamom",
        "cardamom pod",
        "green cardamom",
        "black cardamom",
        "brown cardamom",
        "white cardamom",
        "ground cardamom",
        "cardamom seed",

        # Star anise / Fennel / Anise
        "star anise",
        "whole star anise",
        "ground star anise",
        "aniseed",
        "anise seed",
        "star aniseed",
        "fennel seed",
        "ground fennel",
        "toasted fennel seed",
        "anise",

        # Mustard
        "mustard seed",
        "yellow mustard seed",
        "brown mustard seed",
        "black mustard seed",
        "mustard powder",
        "dry mustard",
        "english mustard powder",
        "coles mustard powder",

        # Fenugreek / Asafoetida / Amchur
        "fenugreek",
        "fenugreek seed",
        "methi seed",
        "dried fenugreek leaf",
        "kasuri methi",
        "fenugreek powder",
        "asafoetida",
        "hing",
        "amchur",
        "amchoor",
        "dried mango powder",
        "mango powder",

        # Saffron
        "saffron",
        "saffron strand",
        "saffron thread",
        "saffron powder",

        # Herb & spice blends
        "garam masala",
        "garam masala powder",
        "curry powder",
        "mild curry powder",
        "madras curry powder",
        "hot curry powder",
        "vindaloo curry powder",
        "tikka masala powder",
        "tandoori masala",
        "biryani masala",
        "chaat masala",
        "chana masala",
        "sambar powder",
        "rasam powder",
        "panch phoron",
        "panch phoran",
        "five spice",
        "chinese five spice",
        "japanese seven spice",
        "shichimi togarashi",
        "furikake",
        "zaatar",
        "za atar",
        "sumac",
        "dukkah",
        "duqqa",
        "ras el hanout",
        "baharat",
        "advieh",
        "berbere",
        "mitmita",
        "harissa powder",

        # Western blends
        "mixed herb",
        "dried mixed herb",
        "herbes de provence",
        "italian herb",
        "italian seasoning",
        "mixed spice",
        "pumpkin pie spice",
        "apple pie spice",
        "poultry seasoning",
        "steak seasoning",
        "montreal steak seasoning",
        "cajun seasoning",
        "creole seasoning",
        "jerk seasoning",
        "fajita seasoning",
        "taco seasoning",
        "chilli seasoning",
        "old bay seasoning",
        "seafood seasoning",
        "lemon pepper",
        "lemon pepper seasoning",
        "season all",
        "all purpose seasoning",
        "vegetable seasoning",

        # Oregano / Thyme / Rosemary /Sage (dried)
        "dried oregano",
        "oregano",
        "dried thyme",
        "thyme dried",
        "dried rosemary",
        "rosemary dried",
        "dried sage",
        "sage dried",
        "dried marjoram",
        "marjoram",
        "dried tarragon",
        "tarragon",
        "dried dill",
        "dried basil",
        "dried parsley",
        "dried mint",
        "dried chive",
        "dried chervil",
        "dried savory",
        "dried lovage",

        # Bay leaf / Curry leaf / Lime leaf
        "bay leaf",
        "bay leaves",
        "dried bay leaf",
        "curry leaf",
        "dried curry leaf",
        "kaffir lime leaf",
        "lime leaf",
        "makrut lime leaf",
        "dried lime leaf",

        # Seeds (cooking)
        "sesame seed",
        "white sesame seed",
        "black sesame seed",
        "toasted sesame seed",
        "caraway seed",
        "celery seed",
        "dill seed",
        "poppy seed",
        "ajwain",
        "carom seed",
        "onion seed",
        "juniper berry",
        "juniper",

        # Lemongrass
        "lemongrass",
        "dried lemongrass",
        "lemongrass powder",

        # Vanilla (spice)
        "vanilla pod",
        "vanilla bean",
        "vanilla powder",

        # MSG / Umami
        "msg",
        "monosodium glutamate",
        "accent seasoning",
        "ajinomoto",
        "umami seasoning",
        "dashi powder",
        "hon dashi",

        # General
        "spice",
        "spice blend",
        "spice mix",
        "seasoning",
        "rub",
        "dry rub",
        "bbq rub",
        "marinade dry",
    ],

    # ------------------------------------------------------------------
    # Oils & Vinegars  (also matches old "Oils" category)
    # ------------------------------------------------------------------
    "Oils & Vinegars": [
        # Olive oil
        "extra virgin olive oil",
        "virgin olive oil",
        "olive oil",
        "light olive oil",
        "pomace olive oil",
        "extra virgin",

        # Seed / Nut oils
        "vegetable oil",
        "sunflower oil",
        "rapeseed oil",
        "canola oil",
        "safflower oil",
        "corn oil",
        "maize oil",
        "soybean oil",
        "soya oil",
        "groundnut oil",
        "peanut oil",
        "sesame oil",
        "toasted sesame oil",
        "coconut oil",
        "avocado oil",
        "grapeseed oil",
        "walnut oil",
        "hazelnut oil",
        "almond oil",
        "flaxseed oil",
        "linseed oil",
        "hemp oil",
        "pumpkin seed oil",
        "macadamia oil",
        "rice bran oil",
        "mustard oil",
        "palm oil",
        "argan oil",

        # Flavoured / Infused oils
        "chilli oil",
        "chili oil",
        "garlic oil",
        "truffle oil",
        "white truffle oil",
        "black truffle oil",
        "herb oil",
        "basil oil",
        "rosemary oil",
        "lemon oil",
        "chive oil",

        # Fats (solid at room temp)
        "ghee",
        "clarified butter",
        "lard",
        "beef dripping",
        "duck fat",
        "goose fat",
        "suet",
        "vegetable suet",
        "shortening",
        "vegetable shortening",
        "trex",
        "crisco",
        "copha",
        "coconut fat",

        # Cooking sprays
        "cooking spray",
        "oil spray",
        "baking spray",
        "fry light",
        "one cal spray",

        # General oil
        "cooking oil",
        "frying oil",
        "salad oil",
        "oil",

        # Vinegar
        "white vinegar",
        "distilled vinegar",
        "spirit vinegar",
        "malt vinegar",
        "brown vinegar",
        "cider vinegar",
        "apple cider vinegar",
        "red wine vinegar",
        "white wine vinegar",
        "balsamic vinegar",
        "balsamic vinegar of modena",
        "aged balsamic vinegar",
        "white balsamic vinegar",
        "rice vinegar",
        "rice wine vinegar",
        "seasoned rice vinegar",
        "sushi vinegar",
        "black vinegar",
        "chinkiang vinegar",
        "chinese black vinegar",
        "sherry vinegar",
        "champagne vinegar",
        "raspberry vinegar",
        "tarragon vinegar",
        "coconut vinegar",
        "cane vinegar",
        "date vinegar",
        "vinegar",

        # Mirin / Cooking wine
        "mirin",
        "hon mirin",
        "aji mirin",
        "cooking sake",
        "cooking wine",
        "shaoxing wine",
        "shaoxing rice wine",
        "rice wine",
        "chinese cooking wine",
        "sake",
    ],

    # ------------------------------------------------------------------
    # Sauces & Condiments  (also matches old "Condiments" category)
    # ------------------------------------------------------------------
    "Sauces & Condiments": [
        # Soy / Tamari / Fish
        "soy sauce",
        "dark soy sauce",
        "light soy sauce",
        "low sodium soy sauce",
        "sweet soy sauce",
        "kecap manis",
        "tamari",
        "tamari sauce",
        "coconut aminos",
        "liquid aminos",
        "fish sauce",
        "nam pla",
        "nuoc mam",
        "thai fish sauce",
        "korean fish sauce",
        "oyster sauce",
        "mushroom soy sauce",
        "mushroom sauce",
        "hoisin sauce",
        "hoisin",

        # Worcestershire / Steak / Brown
        "worcestershire sauce",
        "worcester sauce",
        "lea and perrins",
        "brown sauce",
        "hp sauce",
        "a1 sauce",
        "steak sauce",
        "daddies sauce",

        # Tomato / BBQ
        "ketchup",
        "tomato ketchup",
        "tomato sauce",
        "bbq sauce",
        "barbecue sauce",
        "smoky bbq sauce",
        "hickory bbq sauce",
        "chipotle bbq sauce",
        "kansas city bbq",
        "texas bbq sauce",

        # Mustard
        "dijon mustard",
        "dijon",
        "english mustard",
        "wholegrain mustard",
        "whole grain mustard",
        "french mustard",
        "american mustard",
        "yellow mustard",
        "hot mustard",
        "honey mustard",
        "german mustard",
        "bavarian mustard",
        "coleman mustard",
        "mustard",

        # Mayonnaise / Dressings
        "mayonnaise",
        "mayo",
        "light mayonnaise",
        "kewpie mayonnaise",
        "japanese mayonnaise",
        "aioli",
        "garlic aioli",
        "salad cream",
        "salad dressing",
        "vinaigrette",
        "balsamic dressing",
        "french dressing",
        "italian dressing",
        "ranch dressing",
        "blue cheese dressing",
        "caesar dressing",
        "thousand island dressing",
        "russian dressing",
        "honey mustard dressing",
        "sesame dressing",

        # Hot sauce / Chilli
        "sriracha",
        "sriracha sauce",
        "hot sauce",
        "tabasco",
        "tabasco sauce",
        "cholula",
        "franks red hot",
        "franks hot sauce",
        "louisiana hot sauce",
        "tapatio",
        "valentina",
        "chipotle hot sauce",
        "habanero hot sauce",
        "peri peri sauce",
        "piri piri sauce",
        "nando sauce",
        "harissa paste",
        "harissa",
        "gochujang",
        "gochujang paste",
        "korean chilli paste",
        "ssamjang",
        "doubanjiang",
        "chilli bean paste",
        "toban djan",
        "sambal",
        "sambal oelek",
        "sambal badjak",
        "chilli paste",
        "chilli sauce",
        "sweet chilli sauce",
        "sweet chili sauce",
        "chilli jam",
        "chili jam",

        # Curry pastes
        "curry paste",
        "red curry paste",
        "green curry paste",
        "yellow curry paste",
        "massaman curry paste",
        "panang curry paste",
        "thai red curry paste",
        "thai green curry paste",
        "korma paste",
        "tikka paste",
        "madras paste",
        "vindaloo paste",
        "balti paste",
        "rogan josh paste",
        "rendang paste",
        "laksa paste",
        "satay paste",
        "tandoori paste",

        # Miso / Doenjang
        "miso paste",
        "white miso",
        "red miso",
        "yellow miso",
        "brown miso",
        "barley miso",
        "hatcho miso",
        "saikyo miso",
        "awase miso",
        "miso",
        "doenjang",
        "doenjang paste",
        "korean soybean paste",

        # Other Asian sauces
        "teriyaki sauce",
        "teriyaki",
        "tonkatsu sauce",
        "tonkatsu",
        "okonomiyaki sauce",
        "okonomi sauce",
        "bulgogi sauce",
        "bulgogi",
        "eel sauce",
        "unagi sauce",
        "ponzu",
        "ponzu sauce",
        "yuzu ponzu",
        "tsuyu",
        "mentsuyu",
        "yakisoba sauce",
        "soba tsuyu",
        "tempura dipping sauce",
        "tentsuyu",
        "sukiyaki sauce",
        "shabu shabu sauce",
        "goma dare",
        "sesame dipping sauce",
        "satay sauce",
        "peanut sauce",
        "peanut satay sauce",
        "katsu sauce",
        "buldak sauce",

        # Pesto / Chimichurri
        "pesto",
        "basil pesto",
        "green pesto",
        "red pesto",
        "sun dried tomato pesto",
        "rocket pesto",
        "kale pesto",
        "pistachio pesto",
        "truffle pesto",
        "chimichurri",
        "chimichurri sauce",
        "salsa verde",
        "gremolata",

        # Salsa / Guac / Dips
        "salsa",
        "tomato salsa",
        "picante sauce",
        "pico de gallo",
        "guacamole",
        "guac",
        "hummus",
        "houmous",
        "baba ganoush",
        "babaganoush",
        "tzatziki",
        "raita",
        "taramasalata",
        "skordalia",
        "muhammara",

        # Horseradish / Mint / Apple / Cranberry
        "horseradish sauce",
        "horseradish",
        "creamed horseradish",
        "mint sauce",
        "mint jelly",
        "apple sauce",
        "cranberry sauce",
        "lingonberry jam",
        "redcurrant jelly",

        # Tamarind / Shrimp paste / Belacan
        "tamarind paste",
        "tamarind concentrate",
        "tamarind pulp",
        "shrimp paste",
        "belacan",
        "belachan",
        "terasi",
        "bagoong",
        "anchovy paste",
        "anchovy essence",
        "gentleman relish",
        "patum peperium",

        # Fermented / Pickled pastes
        "fermented black bean",
        "black bean paste",
        "black bean sauce",
        "yellow bean sauce",
        "hoisin",
        "plum sauce",
        "duck sauce",
        "sweet bean sauce",
        "tian mian jiang",
        "chee hou sauce",
        "char siu sauce",

        # Other condiments
        "tahini",
        "tahina",
        "light tahini",
        "dark tahini",
        "pomegranate molasses",
        "date molasses",
        "carob molasses",
        "balsamic glaze",
        "balsamic reduction",
        "verjuice",
        "verjus",
        "maggie seasoning",
        "maggi liquid seasoning",
        "sazon",
        "adobo seasoning",
        "sofrito",
        "recaito",
        "mole paste",
        "mole",
        "achiote paste",
        "annatto paste",
        "achiote",
        "sazon goya",
        "goya adobo",

        # Tartare / Remoulade / Cocktail
        "tartare sauce",
        "tartar sauce",
        "remoulade",
        "cocktail sauce",
        "marie rose sauce",
        "thousand island",

        # Hollandaise / Bearnaise
        "hollandaise sauce",
        "hollandaise",
        "bearnaise sauce",
        "bearnaise",
        "sauce",

        # Concentrates / Pastes
        "tomato puree",
        "tomato paste",
        "tomato concentrate",
        "garlic paste",
        "ginger paste",
        "garlic ginger paste",
        "lemongrass paste",
        "anchovy paste",
        "bouillon paste",
        "stock paste",
        "better than bouillon",

        # Vegan / alternative
        "vegan mayonnaise",
        "vegan mayo",
        "vegan pesto",
        "vegan cheese sauce",
        "nutritional yeast",
        "nooch",

        # General
        "condiment",
        "table sauce",
        "dipping sauce",
        "marinade",
    ],

    # ------------------------------------------------------------------
    # Frozen
    # ------------------------------------------------------------------
    "Frozen": [
        # Frozen vegetables
        "frozen pea",
        "frozen petit pois",
        "frozen garden pea",
        "frozen sweetcorn",
        "frozen corn",
        "frozen spinach",
        "frozen chopped spinach",
        "frozen broccoli",
        "frozen cauliflower",
        "frozen green bean",
        "frozen brussels sprout",
        "frozen carrot",
        "frozen mixed vegetable",
        "frozen vegetable medley",
        "frozen stir fry vegetable",
        "frozen pepper mix",
        "frozen chopped onion",
        "frozen mushroom",
        "frozen butternut squash",
        "frozen sweet potato",
        "frozen roast potato",
        "frozen chip",
        "oven chip",
        "french fry",
        "frozen fry",
        "frozen hash brown",
        "frozen potato wedge",
        "frozen croquette",
        "frozen mashed potato",
        "frozen potato",
        "frozen vegetable",

        # Frozen fruit
        "frozen berry",
        "frozen mixed berry",
        "frozen strawberry",
        "frozen raspberry",
        "frozen blueberry",
        "frozen blackberry",
        "frozen mango",
        "frozen pineapple",
        "frozen peach",
        "frozen cherry",
        "frozen fruit",
        "frozen smoothie mix",
        "frozen acai",
        "frozen pitaya",
        "frozen dragon fruit",

        # Frozen meat / fish
        "frozen chicken breast",
        "frozen chicken",
        "frozen turkey",
        "frozen beef",
        "frozen mince",
        "frozen burger",
        "frozen meatball",
        "frozen sausage",
        "frozen fish fillet",
        "frozen fish",
        "frozen cod",
        "frozen haddock",
        "frozen salmon",
        "frozen prawn",
        "frozen shrimp",
        "frozen squid",
        "frozen seafood mix",
        "frozen seafood",

        # Frozen ready meals / Snacks
        "frozen pizza",
        "frozen ready meal",
        "frozen curry",
        "frozen lasagne",
        "frozen pie",
        "frozen quiche",
        "frozen spring roll",
        "frozen samosa",
        "frozen pakora",
        "frozen bhaji",
        "frozen dim sum",
        "frozen dumpling",
        "frozen gyoza",
        "frozen wonton",
        "frozen mozzarella stick",
        "frozen jalapeno popper",
        "frozen onion ring",
        "frozen garlic bread",
        "frozen garlic baguette",

        # Frozen bread / Pastry
        "frozen pastry",
        "frozen puff pastry",
        "frozen filo pastry",
        "frozen shortcrust pastry",
        "frozen pizza dough",
        "frozen bread dough",
        "frozen bread roll",
        "frozen bagel",
        "frozen croissant",
        "frozen pain au chocolat",
        "frozen pancake",
        "frozen waffle",
        "frozen yorkshire pudding",
        "frozen dough",

        # Ice cream / Desserts
        "ice cream",
        "vanilla ice cream",
        "chocolate ice cream",
        "strawberry ice cream",
        "gelato",
        "sorbet",
        "lemon sorbet",
        "mango sorbet",
        "raspberry sorbet",
        "frozen yogurt",
        "frozen dessert",
        "arctic roll",
        "viennetta",
        "frozen cheesecake",
        "frozen cake",
        "frozen gateau",
        "frozen profiterole",
        "frozen choux bun",
        "frozen eclair",
        "ice lolly",
        "ice pop",
        "popsicle",
        "choc ice",
        "frozen dessert",

        # Ice
        "ice cube",
        "crushed ice",

        # General
        "frozen",
        "freezer",
        "from frozen",
    ],

    # ------------------------------------------------------------------
    # Beverages
    # ------------------------------------------------------------------
    "Beverages": [
        # Water
        "mineral water",
        "sparkling water",
        "still water",
        "spring water",
        "tonic water",
        "soda water",
        "club soda",
        "seltzer",
        "carbonated water",
        "fizzy water",
        "bottled water",
        "water",

        # Juice
        "orange juice",
        "apple juice",
        "grape juice",
        "cranberry juice",
        "pineapple juice",
        "grapefruit juice",
        "tomato juice",
        "mango juice",
        "pomegranate juice",
        "carrot juice",
        "beetroot juice",
        "lemon juice bottled",
        "lime juice bottled",
        "prune juice",
        "coconut water",
        "vegetable juice",
        "fruit juice",
        "smoothie",
        "protein shake",
        "juice",

        # Soft drinks
        "lemonade",
        "traditional lemonade",
        "cloudy lemonade",
        "limeade",
        "cola",
        "cola drink",
        "diet cola",
        "ginger ale",
        "ginger beer",
        "tonic",
        "bitter lemon",
        "dandelion and burdock",
        "elderflower cordial",
        "elderflower presse",
        "shandy",
        "root beer",
        "cream soda",
        "irn bru",
        "lucozade",
        "energy drink",
        "sports drink",
        "isotonic drink",
        "soft drink",
        "fizzy drink",
        "soda",
        "pop",

        # Cordials & Squashes
        "cordial",
        "squash",
        "orange squash",
        "blackcurrant squash",
        "elderflower cordial",
        "lime cordial",
        "rose cordial",
        "fruit syrup",
        "grenadine",
        "diluting juice",

        # Tea
        "black tea",
        "breakfast tea",
        "english breakfast tea",
        "earl grey tea",
        "lady grey tea",
        "darjeeling tea",
        "assam tea",
        "ceylon tea",
        "lapsang souchong",
        "green tea",
        "sencha",
        "matcha",
        "matcha green tea",
        "jasmine tea",
        "white tea",
        "oolong tea",
        "pu erh tea",
        "pu-erh",
        "rooibos",
        "redbush tea",
        "chai tea",
        "chai",
        "masala chai",
        "peppermint tea",
        "chamomile tea",
        "camomile tea",
        "herbal tea",
        "fruit tea",
        "lemon ginger tea",
        "nettle tea",
        "fennel tea",
        "echinacea tea",
        "detox tea",
        "tea bag",
        "loose leaf tea",
        "tea",

        # Coffee
        "coffee",
        "instant coffee",
        "ground coffee",
        "coffee bean",
        "espresso bean",
        "whole bean coffee",
        "filter coffee",
        "cafetiere coffee",
        "decaf coffee",
        "decaffeinated coffee",
        "coffee pod",
        "coffee capsule",
        "nespresso",
        "dolce gusto",
        "tassimo",
        "coffee bag",
        "coffee granule",
        "coffee powder",

        # Milk alternatives
        "almond milk",
        "soy milk",
        "soya milk",
        "oat milk",
        "coconut milk drink",
        "rice milk",
        "cashew milk",
        "hemp milk",
        "hazelnut milk",
        "macadamia milk",
        "barista oat milk",
        "barista almond milk",
        "barista milk",
        "plant milk",
        "dairy free milk",
        "non dairy milk",

        # Milk drinks
        "chocolate milk",
        "strawberry milk",
        "milkshake",
        "protein milk",
        "flavoured milk",

        # Hot chocolate / Malted drinks
        "hot chocolate",
        "drinking chocolate",
        "cocoa powder",
        "cocoa drink",
        "malted drink",
        "horlicks",
        "ovaltine",
        "milo",
        "bournvita",

        # Fermented drinks
        "kombucha",
        "kefir drink",
        "water kefir",
        "kvass",

        # Alcohol (for cooking)
        "white wine",
        "dry white wine",
        "red wine",
        "dry red wine",
        "rose wine",
        "sparkling wine",
        "champagne",
        "prosecco",
        "cava",
        "cider",
        "dry cider",
        "beer",
        "lager",
        "ale",
        "stout",
        "guinness",
        "porter",
        "bitter",
        "ipa",
        "brandy",
        "cognac",
        "armagnac",
        "calvados",
        "rum",
        "white rum",
        "dark rum",
        "vodka",
        "gin",
        "whisky",
        "whiskey",
        "scotch",
        "bourbon",
        "tequila",
        "mezcal",
        "sherry",
        "dry sherry",
        "fino sherry",
        "amontillado",
        "port",
        "madeira",
        "marsala",
        "vermouth",
        "dry vermouth",
        "sweet vermouth",
        "martini",
        "campari",
        "aperol",
        "liqueur",
        "cointreau",
        "triple sec",
        "grand marnier",
        "amaretto",
        "frangelico",
        "kahlua",
        "baileys",
        "irish cream",
        "tia maria",
        "kirsch",
        "cherry brandy",
        "pernod",
        "pastis",
        "ouzo",
        "sambuca",
        "limoncello",
        "cassis",
        "chambord",
        "drambuie",

        # General
        "beverage",
        "drink",
        "bottle",
    ],

    # ------------------------------------------------------------------
    # Fresh Herbs
    # ------------------------------------------------------------------
    "Fresh Herbs": [
        # Basil
        "basil",
        "fresh basil",
        "thai basil",
        "holy basil",
        "tulsi",
        "lemon basil",
        "greek basil",
        "purple basil",
        "sweet basil",

        # Coriander / Cilantro
        "coriander",
        "fresh coriander",
        "cilantro",
        "vietnamese coriander",
        "rau ram",
        "culantro",
        "recao",
        "sawtooth coriander",
        "sawtooth herb",

        # Parsley
        "parsley",
        "fresh parsley",
        "flat leaf parsley",
        "italian parsley",
        "curly parsley",
        "continental parsley",

        # Mint
        "mint",
        "fresh mint",
        "peppermint",
        "spearmint",
        "apple mint",
        "pineapple mint",
        "chocolate mint",
        "lemon mint",
        "moroccan mint",
        "vietnamese mint",
        "fish mint",

        # Dill
        "dill",
        "fresh dill",
        "dill weed",

        # Chives
        "chive",
        "fresh chive",
        "garlic chive",
        "chinese chive",

        # Rosemary
        "rosemary",
        "fresh rosemary",

        # Thyme
        "thyme",
        "fresh thyme",
        "lemon thyme",
        "wild thyme",
        "creeping thyme",

        # Sage
        "sage",
        "fresh sage",
        "pineapple sage",

        # Oregano / Marjoram
        "oregano",
        "fresh oregano",
        "marjoram",
        "fresh marjoram",
        "pot marjoram",
        "wild marjoram",

        # Tarragon
        "tarragon",
        "fresh tarragon",
        "french tarragon",
        "russian tarragon",
        "mexican tarragon",

        # Chervil
        "chervil",
        "fresh chervil",

        # Bay / Lime leaf
        "bay leaf fresh",
        "fresh bay leaf",
        "fresh bay leaves",
        "curry leaf fresh",
        "fresh curry leaf",
        "lime leaf fresh",
        "fresh lime leaf",
        "kaffir lime leaf fresh",
        "fresh kaffir lime leaf",
        "pandan leaf",
        "pandan",
        "screwpine",

        # Lemongrass
        "lemongrass",
        "fresh lemongrass",

        # Savory
        "savory",
        "fresh savory",
        "summer savory",
        "winter savory",

        # Lovage / Borage
        "lovage",
        "fresh lovage",
        "borage",
        "fresh borage",
        "lemon verbena",
        "lemon balm",
        "fresh lemon balm",

        # Sorrel
        "sorrel",
        "fresh sorrel",

        # Shiso / Perilla
        "shiso",
        "perilla",
        "perilla leaf",
        "red shiso",
        "green shiso",

        # Epazote
        "epazote",
        "fresh epazote",

        # Cress / Microgreens
        "cress",
        "mustard cress",
        "garden cress",
        "microgreen",
        "micro herb",
        "pea shoot",
        "sunflower shoot",
        "radish sprout",
        "beetroot sprout",

        # Nasturtium / Edible flowers
        "nasturtium",
        "nasturtium leaf",
        "nasturtium flower",
        "edible flower",
        "marigold",
        "calendula",
        "borage flower",
        "chive flower",
        "rose petal",
        "viola",
        "pansy",
        "lavender",
        "fresh lavender",

        # Herb mixes
        "mixed fresh herb",
        "fresh herb mix",
        "bouquet garni fresh",
        "pot herb",
        "fresh herb",
        "herb bunch",
    ],

    # ------------------------------------------------------------------
    # Nuts & Seeds
    # ------------------------------------------------------------------
    "Nuts & Seeds": [
        # Tree nuts
        "almond",
        "blanched almond",
        "flaked almond",
        "slivered almond",
        "almond sliver",
        "whole almond",
        "ground almond",
        "almond meal",
        "almond flake",
        "smoked almond",
        "roasted almond",
        "marcona almond",
        "walnut",
        "walnut half",
        "walnut piece",
        "chopped walnut",
        "black walnut",
        "pecan",
        "pecan half",
        "chopped pecan",
        "candied pecan",
        "cashew",
        "cashew nut",
        "roasted cashew",
        "salted cashew",
        "raw cashew",
        "cashew piece",
        "pistachio",
        "shelled pistachio",
        "roasted pistachio",
        "salted pistachio",
        "unsalted pistachio",
        "pistachio kernel",
        "hazelnut",
        "cobnut",
        "filbert",
        "roasted hazelnut",
        "blanched hazelnut",
        "chopped hazelnut",
        "ground hazelnut",
        "macadamia",
        "macadamia nut",
        "roasted macadamia",
        "brazil nut",
        "pine nut",
        "pine kernel",
        "pignoli",
        "toasted pine nut",
        "chestnut",
        "roasted chestnut",
        "vacuum packed chestnut",
        "chestnut puree",
        "water chestnut",
        "coconut",
        "shredded coconut",
        "desiccated coconut",
        "coconut flake",
        "coconut chip",
        "coconut strip",
        "toasted coconut",
        "creamed coconut",
        "coconut block",

        # Peanuts / Groundnuts
        "peanut",
        "raw peanut",
        "roasted peanut",
        "dry roasted peanut",
        "salted peanut",
        "unsalted peanut",
        "blanched peanut",
        "red skin peanut",
        "spanish peanut",
        "valencia peanut",
        "groundnut",
        "peanut half",

        # Mixed nuts / Trail mix
        "mixed nut",
        "nut mix",
        "trail mix",
        "fruit and nut mix",
        "student mix",

        # Seeds
        "sunflower seed",
        "sunflower kernel",
        "toasted sunflower seed",
        "pumpkin seed",
        "pepita",
        "toasted pumpkin seed",
        "sesame seed",
        "white sesame seed",
        "black sesame seed",
        "toasted sesame seed",
        "flaxseed",
        "linseed",
        "golden flaxseed",
        "brown flaxseed",
        "ground flaxseed",
        "milled flaxseed",
        "chia seed",
        "hemp seed",
        "hemp heart",
        "poppy seed",
        "nigella seed",
        "kalonji",
        "cumin seed",
        "fennel seed",
        "caraway seed",
        "celery seed",
        "mustard seed",
        "anise seed",
        "coriander seed",

        # Nut butters / spreads
        "peanut butter",
        "smooth peanut butter",
        "crunchy peanut butter",
        "almond butter",
        "cashew butter",
        "tahini",
        "tahina",
        "sesame paste",
        "hazelnut spread",
        "chocolate hazelnut spread",
        "nutella",
        "sunflower seed butter",
        "mixed nut butter",
        "nut butter",

        # Nut pastes / marzipan
        "marzipan",
        "almond paste",
        "pistachio paste",
        "hazelnut paste",
        "praline paste",
        "nut paste",

        # General
        "nut",
        "seed",
        "kernel",
        "nut and seed mix",
    ],

    # ------------------------------------------------------------------
    # Baking Supplies
    # ------------------------------------------------------------------
    "Baking Supplies": [
        # Flour
        "plain flour",
        "all purpose flour",
        "self raising flour",
        "self rising flour",
        "bread flour",
        "strong flour",
        "strong white flour",
        "strong brown flour",
        "cake flour",
        "pastry flour",
        "whole wheat flour",
        "wholemeal flour",
        "spelt flour",
        "rye flour",
        "dark rye flour",
        "light rye flour",
        "oat flour",
        "rice flour",
        "glutinous rice flour",
        "coconut flour",
        "almond flour",
        "ground almond",
        "hazelnut flour",
        "chickpea flour",
        "gram flour",
        "besan",
        "buckwheat flour",
        "teff flour",
        "millet flour",
        "sorghum flour",
        "quinoa flour",
        "soy flour",
        "cornflour",
        "corn starch",
        "cornstarch",
        "tapioca flour",
        "tapioca starch",
        "potato starch",
        "potato flour",
        "arrowroot",
        "arrowroot powder",
        "gluten free flour",
        "gluten free plain flour",
        "gluten free self raising flour",
        "gluten free bread flour",
        "doves farm",
        "freee flour",
        "flour",

        # Sugar
        "granulated sugar",
        "white sugar",
        "caster sugar",
        "superfine sugar",
        "golden caster sugar",
        "icing sugar",
        "powdered sugar",
        "confectioners sugar",
        "brown sugar",
        "light brown sugar",
        "dark brown sugar",
        "soft brown sugar",
        "muscovado sugar",
        "light muscovado",
        "dark muscovado",
        "demerara sugar",
        "turbinado sugar",
        "coconut sugar",
        "palm sugar",
        "jaggery",
        "panela",
        "piloncillo",
        "vanilla sugar",
        "cinnamon sugar",
        "sugar cube",
        "preserving sugar",
        "jam sugar",
        "sugar",

        # Sweeteners
        "stevia",
        "erythritol",
        "xylitol",
        "monk fruit sweetener",
        "splenda",
        "canderel",
        "sweetener",
        "artificial sweetener",

        # Leavening agents
        "yeast",
        "active dry yeast",
        "instant yeast",
        "fast action yeast",
        "easy bake yeast",
        "fresh yeast",
        "compressed yeast",
        "sourdough starter",
        "levain",
        "baking powder",
        "gluten free baking powder",
        "baking soda",
        "bicarbonate of soda",
        "bicarb",
        "bread soda",
        "cream of tartar",
        "potassium bitartrate",
        "ammonium bicarbonate",
        "bakers ammonia",
        "hartshorn",
        "smelling salt",

        # Chocolate
        "dark chocolate",
        "milk chocolate",
        "white chocolate",
        "cooking chocolate",
        "baking chocolate",
        "couverture chocolate",
        "chocolate chip",
        "dark chocolate chip",
        "milk chocolate chip",
        "white chocolate chip",
        "chocolate chunk",
        "chocolate callet",
        "chocolate button",
        "chocolate drop",
        "chocolate coating",
        "candy melt",
        "chocolate",

        # Cocoa
        "cocoa powder",
        "cacao powder",
        "cocoa",
        "cacao",
        "dutch processed cocoa",
        "dutch cocoa",
        "natural cocoa powder",
        "raw cacao powder",
        "cacao nib",
        "cocoa nib",
        "cocoa butter",
        "cacao butter",

        # Extracts & Flavourings
        "vanilla extract",
        "vanilla essence",
        "vanilla paste",
        "vanilla bean paste",
        "vanilla pod",
        "vanilla bean",
        "vanilla powder",
        "almond extract",
        "almond essence",
        "peppermint extract",
        "peppermint essence",
        "orange extract",
        "lemon extract",
        "coffee extract",
        "coconut extract",
        "rum flavouring",
        "brandy flavouring",
        "maple extract",
        "banana extract",
        "strawberry flavouring",
        "raspberry flavouring",
        "pandan extract",
        "pandan paste",
        "flavouring",
        "essence",
        "extract",

        # Floral waters
        "rose water",
        "orange blossom water",
        "orange flower water",
        "rose extract",
        "kewra water",
        "screwpine water",

        # Food colouring
        "food colouring",
        "food coloring",
        "gel food colouring",
        "liquid food colouring",
        "natural food colouring",
        "food colour paste",
        "food colour gel",
        "food colour powder",
        "edible lustre",
        "edible glitter",
        "edible gold leaf",
        "edible silver leaf",

        # Decoration
        "sprinkle",
        "hundreds and thousands",
        "sugar strand",
        "coloured sprinkle",
        "chocolate sprinkle",
        "vermicelli sprinkle",
        "sugar pearl",
        "edible glitter",
        "edible star",
        "edible heart",
        "cake decoration",
        "sugar paste decoration",
        "sugar flower",
        "wafer flower",
        "wafer paper",
        "rice paper sheet",
        "edible image",

        # Setting agents
        "gelatin",
        "gelatine",
        "gelatin leaf",
        "gelatine leaf",
        "sheet gelatin",
        "powdered gelatin",
        "gelatin powder",
        "agar agar",
        "agar agar powder",
        "agar flake",
        "vege gel",
        "vegetarian gelatin",
        "pectin",
        "jam sugar with pectin",
        "liquid pectin",
        "powdered pectin",
        "xanthan gum",
        "guar gum",
        "locust bean gum",
        "carrageenan",
        "tapioca starch",
        "arrowroot",
        "corn starch",

        # Icings / Fondant
        "fondant icing",
        "ready to roll icing",
        "sugar paste",
        "modelling paste",
        "flower paste",
        "gum paste",
        "petal paste",
        "mexican paste",
        "royal icing",
        "royal icing powder",
        "instant royal icing",
        "buttercream",
        "frosting",
        "glacé icing",
        "glaze icing",
        "drip icing",
        "mirror glaze",
        "cake covering",
        "marzipan",
        "white marzipan",
        "golden marzipan",
        "almond paste",

        # Cake / Dessert mixes
        "cake mix",
        "sponge mix",
        "brownie mix",
        "cookie mix",
        "muffin mix",
        "scone mix",
        "pancake mix",
        "waffle mix",
        "bread mix",
        "pizza dough mix",
        "pastry mix",
        "batter mix",
        "crumpet mix",
        "yorkshire pudding mix",
        "blancmange mix",
        "custard powder",
        "instant custard",
        "jelly crystal",
        "jelly mix",
        "instant pudding",
        "angel delight",
        "dessert mix",

        # Other baking ingredients
        "custard powder",
        "cornflour",
        "golden syrup",
        "maple syrup",
        "honey",
        "treacle",
        "black treacle",
        "molasses",
        "glucose syrup",
        "liquid glucose",
        "corn syrup",
        "malt extract",
        "malt powder",
        "dried milk powder",
        "skimmed milk powder",
        "buttermilk powder",
        "buttermilk blend",
        "coconut milk powder",
        "coffee powder instant",
        "espresso powder",
        "instant espresso",
        "dried egg white",
        "meringue powder",
        "egg replacer",
        "egg substitute powder",
        "dried yeast",
        "bread improver",
        "dough enhancer",
        "vital wheat gluten",
        "seitan flour",
        "gluten flour",
        "diastatic malt powder",
        "non diastatic malt powder",
        "ascorbic acid",
        "vitamin c powder",
        "citric acid",
        "cream of tartar",
        "glucose",
        "dextrose",
        "fructose",
        "maltodextrin",
        "invert sugar",
        "trimoline",
        "isomalt",
        "glycerine",
        "glycerol",
        "lecithin",
        "soy lecithin",
        "sunflower lecithin",
        "baking fat",
        "block margarine",
        "baking margarine",
        "hard margarine",
        "white fat",
        "vegetable shortening",
        "trex",
        "crisco",
        "lard",
        "suet",
        "coconut oil solid",
        "copha",
        "kremelta",
        "baking",
    ],

    # ------------------------------------------------------------------
    # Deli
    # ------------------------------------------------------------------
    "Deli": [
        # Cooked / Sliced Meats
        "sliced ham",
        "wafer thin ham",
        "honey roast ham",
        "smoked ham",
        "cooked ham",
        "york ham",
        "black forest ham",
        "prosciutto cotto",
        "roast turkey",
        "turkey breast sliced",
        "smoked turkey",
        "roast chicken",
        "chicken breast sliced",
        "roast beef",
        "sliced beef",
        "salt beef",
        "roast pork",
        "roast lamb",
        "tongue",
        "pressed tongue",
        "ox tongue",
        "haslet",

        # Cured / Dried Meats
        "prosciutto",
        "prosciutto crudo",
        "prosciutto di parma",
        "parma ham",
        "serrano ham",
        "jamon serrano",
        "iberico ham",
        "jamón ibérico",
        "speck",
        "bresaola",
        "coppa",
        "capicola",
        "coppa di parma",
        "bündnerfleisch",
        "viande des grisons",
        "cured ham",
        "cured meat",
        "air dried beef",

        # Salami / Sausages
        "salami",
        "milan salami",
        "napoli salami",
        "fennel salami",
        "hungarian salami",
        "german salami",
        "danish salami",
        "pepperoni",
        "chorizo",
        "spanish chorizo",
        "chorizo iberico",
        "lomo",
        "lomo embuchado",
        "fuet",
        "sobrassada",
        "soppressata",
        "finocchiona",
        "cacciatore",
        "cacciatorini",
        "landjager",
        "cervelat",
        "saucisson sec",
        "saucisson",
        "rosette de lyon",
        "summer sausage",
        "mortadella",
        "mortadella bologna",
        "bologna",
        "polony",
        "luncheon meat",
        "devon",
        "fritz",
        "strasbourg",
        "cabana",
        "krakauer",
        "bierwurst",
        "jagdwurst",
        "fleischwurst",
        "extrawurst",
        "lyoner",
        "gelbwurst",
        "weißwurst",
        "weisswurst",

        # Pâté / Terrine
        "paté",
        "pâté",
        "pate",
        "chicken liver pate",
        "duck pate",
        "pork pate",
        "mushroom pate",
        "vegetarian pate",
        "terrine",
        "terrine de campagne",
        "country terrine",
        "game terrine",
        "salmon terrine",
        "foie gras",
        "foie gras pate",
        "rillettes",
        "pork rillettes",
        "duck rillettes",
        "chicken rillettes",
        "salmon rillettes",
        "potted meat",
        "potted shrimp",
        "potted crab",

        # Smoked Fish
        "smoked salmon",
        "oak smoked salmon",
        "wild smoked salmon",
        "gravlax",
        "gravadlax",
        "lox",
        "smoked trout",
        "smoked mackerel",
        "peppered mackerel",
        "smoked eel",
        "smoked haddock",
        "finnan haddie",
        "arbroath smokie",
        "kipper",
        "bloater",
        "buckling",
        "smoked fish",
        "smoked seafood",

        # Pickled / Preserved Fish
        "pickled herring",
        "rollmop",
        "roll mop",
        "soused herring",
        "schmaltz herring",
        "matjes herring",
        "brathering",
        "sild",
        "anchovy",
        "marinated anchovy",
        "boquerones",
        "white anchovy",
        "sprat",
        "brisling",

        # Antipasti / Marinated Vegetables
        "antipasti",
        "olive",
        "mixed olive",
        "stuffed olive",
        "marinated olive",
        "garlic stuffed olive",
        "chilli stuffed olive",
        "almond stuffed olive",
        "anchovy stuffed olive",
        "pimento stuffed olive",
        "sun dried tomato",
        "sundried tomato",
        "semi dried tomato",
        "roasted pepper",
        "chargrilled pepper",
        "marinated pepper",
        "piquillo pepper",
        "grilled artichoke",
        "chargrilled artichoke",
        "marinated artichoke",
        "artichoke heart",
        "grilled aubergine",
        "grilled courgette",
        "grilled zucchini",
        "dolmades",
        "stuffed vine leaf",
        "stuffed grape leaf",
        "sarma",
        "giardiniera",
        "mixed antipasti",
        "antipasti platter",
        "bruschetta topping",
        "crostini topping",
        "tapenade",
        "olive tapenade",
        "black olive tapenade",
        "green olive tapenade",

        # Quiche / Savoury Tarts
        "quiche",
        "quiche lorraine",
        "cheese and onion quiche",
        "broccoli quiche",
        "mushroom quiche",
        "smoked salmon quiche",
        "mini quiche",
        "flamiche",
        "pissaladiere",
        "tarte flambee",
        "flammekueche",
        "savoury tart",
        "cheese tart",
        "onion tart",
        "tomato tart",

        # Pork Pies / Sausage Rolls / Scotch Eggs
        "pork pie",
        "melton mowbray pork pie",
        "hand raised pork pie",
        "picnic pie",
        "gala pie",
        "veal and ham pie",
        "game pie",
        "scotch egg",
        "mini scotch egg",
        "sausage roll",
        "cocktail sausage roll",
        "mini sausage roll",
        "vegan sausage roll",
        "pasty",
        "cornish pasty",
        "cheese and onion pasty",
        "steak pasty",
        "meat pie",
        "steak pie",
        "steak and kidney pie",
        "chicken and mushroom pie",

        # Savoury Bakery
        "spanakopita",
        "spinach and feta pastry",
        "borek",
        "burek",
        "cheese borek",
        "gozleme",
        "khachapuri",
        "empanada",
        "empanadilla",
        "pierogi",
        "perogi",
        "pelmeni",
        "vareniki",
        "knish",
        "calzone",
        "stromboli",
        "focaccia sandwich",
        "panini",
        "ciabatta sandwich",
        "filled croissant",
        "savory croissant",

        # Olives / Capers / Pickles (deli counter)
        "caper",
        "caper berry",
        "cornichon",
        "pickled gherkin",
        "dill pickle spear",
        "pickle half",
        "whole pickle",
        "pickled egg",
        "pickled onion",
        "pickled walnut",
        "pickled garlic",

        # Dips / Spreads
        "hummus",
        "houmous",
        "flavoured hummus",
        "guacamole",
        "guac",
        "taramasalata",
        "tarama",
        "baba ganoush",
        "babaganoush",
        "muhammara",
        "skordalia",
        "tzatziki",
        "taramousalata",
        "cacik",
        "melitzanosalata",
        "htipiti",
        "fava dip",
        "artichoke dip",
        "spinach dip",
        "crab dip",
        "smoked mackerel pate",
        "salmon mousse",
        "cheese spread",
        "cheddar spread",
        "port wine cheese",

        # Cheese from Deli
        "feta",
        "halloumi",
        "mozzarella ball",
        "buffalo mozzarella",
        "bocconcini",
        "manchego",
        "aged gouda",
        "smoked cheese",
        "applewood smoked cheddar",
        "baked camembert",
        "baked brie",
        "goat cheese log",

        # Accompaniments
        "cracker selection",
        "cheese biscuit",
        "breadstick",
        "grissini",
        "oatcake",

        # General
        "deli",
        "delicatessen",
        "charcuterie",
        "charcuterie board",
        "cheese board",
        "antipasto",
        "mixed antipasto",
        "continental selection",
        "cold cut",
        "cooked meat",
        "sandwich filler",
        "sandwich filling",
    ],

    # ------------------------------------------------------------------
    # Other  (catch-all / fallback)
    # ------------------------------------------------------------------
    "Other": [],
}
